### PR TITLE
S2077: Fix False Negative for + operator

### LINKED ISSUE #2417: False negative on Rule S2077: the use of operator + should raise an issue in VB.Net
Rule S2077 should raise when the SQL query is concatenated using the `+` operator in VB.Net.

### PR DESCRIPTION
**Pull request by christophe-zurn-sonarsource**
Fix #2417

### CODE REVIEW

File: sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/ExecutingSqlQueries.cs [hunk 1]
```diff
@@ -95,25 +95,29 @@ protected override bool IsStringMethodInvocation(string methodName, ExpressionSy
         private static bool AllConstants(List<ArgumentSyntax> arguments, SemanticModel semanticModel) =>
             arguments.All(a => a.GetExpression().IsConstant(semanticModel));
 
+        private static bool IsConcatenationOperator(SyntaxNode node)
```
Comment (andrei-epure-sonarsource) [inline sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/ExecutingSqlQueries.cs]: this can use `=>` syntax to improve readability
