### PR TITLE
TestFramework: Implement issue matching

### LINKED ISSUE #8543: TestFramework: List all failed Noncompliant assertions at once

### PR DESCRIPTION
**Pull request by pavel-mikula-sonarsource**
Fixes #8543

Project-level assertions will be restored in #8624 
IssueId assertions will be restored in #8623 
More friendly messages for build errors will be in #8601

### CODE REVIEW

File: analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs [hunk 1]
```diff
@@ -206,87 +182,44 @@ private static void CompareActualToExpected(string languageVersion, Diagnostic[]
...
-                    : extraInfo;
-                throw new UnexpectedDiagnosticException(location, exceptionMessage);
+                ret.AddRange(BestMatch(actualIssues.Remove(key), expectedIssues.Remove(key)));
             }
+            ret.AddRange(expectedIssues.Select(x => new IssueLocationPair(null, x)));
+            return ret;
+        }
 
-            if (expectedIssue.Message != null && expectedIssue.Message != message)
+        private static IEnumerable<IssueLocationPair> BestMatch(List<IssueLocation> actualIssues, List<IssueLocation> expectedIssues)
```
Comment (gregory-paidis-sonarsource) [inline analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs:204]: I don't like the name `BestMatch` that much, since from the caller's perspective, what it does is return the imperfect matches.

I think we should call it something like `FindMismatches`.

File: analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs [hunk 2]
```diff
@@ -141,59 +141,35 @@ ReportDiagnostic Severity(string id)
...
-                        ? $"{languageVersion}: Unexpected build error [{diagnostic.Id}]: {diagnostic.GetMessage()} on line {diagnostic.Location.GetLineNumberToReport()}"
-                        : null);
-
-                var secondaryLocations = diagnostic.AdditionalLocations
-                    .Select((_, i) => diagnostic.GetSecondaryLocation(i))
-                    .OrderBy(x => x.Location.GetLineNumberToReport())
-                    .ThenBy(x => x.Location.GetLineSpan().StartLinePosition.Character);
-
-                foreach (var secondaryLocation in secondaryLocations)
+                if (previousFilePath != pair.FilePath)
```
Comment (gregory-paidis-sonarsource) [inline analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs:152]: this `previousFilePath` variable seems like a roundabout way of doing a groupBy. 
What about something like this:

```csharp
foreach (var pairsByFile in pairs.GroupBy(x => x.FilePath))
{
    if (assertionMessages.Length > 0)
    {
        assertionMessages.AppendLine();
    }
    assertionMessages.AppendLine($"There are differences for {actual.LanguageVersion} {pairsByFile.Key}:");
    foreach (var pair in pairsByFile.OrderBy(x => x.LineNumber).ThenBy(x => x.Start))
    {
        pair.AppendAssertionMessage(assertionMessages);
    }
}
```

IMO it reads a bit more naturally, since you don't have to mentally track the state of the `previousFilePath`.

File: analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs [hunk 3]
```diff
@@ -141,59 +141,35 @@ ReportDiagnostic Severity(string id)
...
-                    var expectedIssuesSecondaryLocation = ExpectedIssues(expectedIssuesPerFile, secondaryLocation.Location);
-                    VerifySecondaryIssue(languageVersion,
-                        expectedIssuesSecondaryLocation,
-                        issue => issue.IssueId == issueId && !issue.IsPrimary,
-                        secondaryLocation.Location,
-                        secondaryLocation.Message,
-                        issueId);
+                    if (assertionMessages.Length > 0)
+                    {
+                        assertionMessages.AppendLine();
```
Comment (gregory-paidis-sonarsource) [inline analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs:156]: I would move this at the end of the loop, and remove the Length-check completely for simplicity.
Worst-case you add an extra new-line at the end.

File: analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs [hunk 4]
```diff
@@ -141,59 +141,35 @@ ReportDiagnostic Severity(string id)
             }
         }
 
-        private static void CompareActualToExpected(string languageVersion, Diagnostic[] diagnostics, FileIssueLocations[] expectedIssuesPerFile, bool compareIdToMessage)
+        private static void CompareActualToExpected(Diagnostic[] diagnostics, CompilationIssues expected, bool compareIdToMessage)
```
Comment (gregory-paidis-sonarsource) [inline analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs:144]: The parameter `compareIdToMessage` is useless (for now).
It's part of the next PR, right?

**Review by gregory-paidis-sonarsource — CHANGES_REQUESTED** [review]
Looks way cleaner, left some suggestions and questions.

File: analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/DiagnosticVerifierTest.cs [hunk 5]
```diff
@@ -29,179 +30,199 @@ public class DiagnosticVerifierTest
...
+                        { }
+                    }
+                }
+                """, """
+                There are differences for CSharp7 snippet1.cs:
+                  Line 5 Secondary location: Unexpected issue ''
+                """);
 
         [TestMethod]
+        [Ignore] // ToDo: Fix in
```
[the remark this answers is not in the document]
Comment (pavel-mikula-sonarsource) [reply analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/DiagnosticVerifierTest.cs:65]: #8623 I forgot to paste the link there. I won't fix it in this PR, as it's already on the way

File: analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs (hunk 4 above)
Comment (pavel-mikula-sonarsource) [reply analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs:144]: I don't know yet. I will either use it or remove it in #8601

**Review by gregory-paidis-sonarsource — APPROVED** [review]
LGTM
