### PR TITLE
ITs: Deduplicate orchestrator initialization

### LINKED ISSUE #6951: ITs: Set SQ version to DEV
When using the "DEV" version of SonarQube our ITs are failing because there's a new warning emitted.
```
WARN: The properties 'sonar.login' and 'sonar.password' are deprecated. They will not be supported in the future. Please instead use the 'sonar.token' parameter.
```

We should:
-  ~update the tests to Assert the warning~ This warning will change and it should disappear from our ITs. We need to wait for SQ to fix this from their side.
-  revert #6950 and #7014 of using the `LATEST_RELEASE[9.9]` of SonarQube.
- changes in #7017 will move those 3 different locations only into a single file in `TestUtils.java`

PS: ~The sonar.token property is not supported by Scanner for .Net yet. If provided there's an error in the end step:
`This setting is not valid in the "end" phase in this version of the C# plugin: sonar.token`
We'll assert the warning until support is implemented.~

### PR DESCRIPTION
**Pull request by pavel-mikula-sonarsource**
Deduplicate version configuration and orchestrator scaffolding to a single place.

### CODE REVIEW

File: its/src/test/java/com/sonar/it/shared/TestUtils.java [hunk 1]
```diff
@@ -70,6 +72,21 @@ public class TestUtils {
...
+  public static OrchestratorBuilder prepareOrchestrator() {
+    return Orchestrator.builderEnv()
+      .useDefaultAdminCredentialsForBuilds(true)
+      // Versions of SonarQube and plugins support aliases:
+      // - "DEV" for the latest build of master that passed QA
+      // - "DEV[1.0]" for the latest build that passed QA of series 1.0.x
+      // - "LATEST_RELEASE" for the latest release
+      // - "LATEST_RELEASE[1.0]" for latest release of series 1.0.x
+      // The SonarQube alias "LTS" has been dropped. An alternative is "LATEST_RELEASE[9.9]".
+      // The term "latest" refers to the highest version number, not the most recently published version.
```
Comment (mary-georgiou-sonarsource) [inline its/src/test/java/com/sonar/it/shared/TestUtils.java:84]: I don't understand this comment (what latest means.)

**Review by mary-georgiou-sonarsource — COMMENTED** [review]
LGTM - only a comment regarding a a comment in the code that is not clear to me.

**Review by mary-georgiou-sonarsource — APPROVED** [review]

File: its/src/test/java/com/sonar/it/shared/TestUtils.java (hunk 1 above)
Comment (pavel-mikula-sonarsource) [reply its/src/test/java/com/sonar/it/shared/TestUtils.java]: Probably something like that version 9.9.0.1002 could have been published later than 9.9.1003.

I've replaced the whole thing with link to the orchestrator readme instead. That one is more up to date.
