### PR TITLE
OutOfMemoryError possible using wildcard pattern with alternative path separators

### LINKED ISSUE #3852: OutOfMemoryError possible using wildcard pattern with alternative path separators
### Description

If you provide a wildcard pattern on Windows with forward slashes, the analyzer may search too high in the directory structure, eventually causing an OutOfMemoryError. It should support paths containing any acceptable path separator, not just the default.

### Repro steps

On Windows, provide an analyzer property such as:

> sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/**/*.trx

Note that my example is on an Azure Pipelines self-hosted agent, so $(Agent.TempDirectory) is similar to `C:\agent_work9`.  

During analysis, you see the following DEBUG output:

```
18:40:23.959 INFO: Sensor C# Unit Test Results Import [csharp]
18:40:23.959 DEBUG: Pattern matcher extracted prefix/absolute path 'C:\agent_work9' from the given pattern 'C:\agent_work9\_temp/**/*.trx'.
18:40:23.959 DEBUG: Gathering files for wildcardPattern '_temp/**/*.trx'.
18:52:34.401 INFO: ------------------------------------------------------------------------
18:52:34.401 INFO: EXECUTION FAILURE
18:52:34.401 INFO: ------------------------------------------------------------------------
18:52:34.401 INFO: Total time: 12:18.950s
18:52:34.448 INFO: Final Memory: 9M/895M
18:52:34.448 INFO: ------------------------------------------------------------------------
##[error]18:52:34.448 ERROR: Error during SonarScanner execution
##[debug]Processed: ##vso[task.logissue type=error;]18:52:34.448 ERROR: Error during SonarScanner execution
18:52:34.448 ERROR: Error during SonarScanner execution
##[error]java.lang.OutOfMemoryError: Java heap space
	at java.io.WinNTFileSystem.resolve(Unknown Source)
	at java.io.File.<init>(Unknown Source)
	at java.io.File.listFiles(Unknown Source)
	at org.sonar.plugins.dotnet.tests.WildcardPatternFileProvider.listFiles(WildcardPatternFileProvider.java:140)
```

Note that the file search starts at `C:\agent_work9` and not `C:\agent_work9\_temp`, which causes it to search through every build ever conducted by this agent, including ancillary tools and packages, etc.

The root cause for this is that the [WildcardPatternFileProvider](https://github.com/SonarSource/sonar-dotnet/blob/8.15.0.24505/sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/WildcardPatternFileProvider.java) class constructor accepts a `directorySeparator` parameter, which is only being provided as the default path separator (File.separator). Perhaps it should take [the same approach as .NET](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#canonicalize-separators) to accept both forward and back slashes.

### Known workarounds

Switch to the default Windows path separators:

> sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/**/*.trx

And it will search at the correct level:
```
22:10:40.179 DEBUG: Pattern matcher extracted prefix/absolute path 'C:\agent_work1\_temp' from the given pattern 'C:\agent_work1\_temp\**\*.trx'.
```

### Related information

* SonarScanner for AzurePipelines 4.17.0
* Azure Pipelines Windows self-hosted agent
* C#
* netcoreapp3.1

### PR DESCRIPTION
**Pull request by csaba-sagi-sonarsource**
Fixes #3852

### CODE REVIEW

File: sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/WildcardPatternFileProvider.java [hunk 1]
```diff
@@ -43,16 +43,14 @@
...
-  public WildcardPatternFileProvider(File baseDir, String directorySeparator) {
+  public WildcardPatternFileProvider(File baseDir) {
     this.baseDir = baseDir;
-    this.directorySeparator = directorySeparator;
   }
 
   Set<File> listFiles(String pattern) {
 
-    List<String> elements = Arrays.asList(pattern.split(Pattern.quote(directorySeparator)));
+    List<String> elements = Arrays.asList(pattern.split("["+ Pattern.quote(File.separator) +"/]"));
```
Comment (andrei-epure-sonarsource) [inline sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/WildcardPatternFileProvider.java:53]: can the `"["+ Pattern.quote(File.separator) +"/]"` be in a static final field? to avoid doing string concatenations at each call?

File: sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/WildcardPatternFileProviderTest.java [hunk 2]
```diff
@@ -236,6 +236,17 @@ public void should_fail_with_parent_folder_access_after_wildcard() {
     listFiles(path("*", "..", "foo.txt"), tmp.getRoot());
   }
 
+  @Test
+  public void given_pattern_with_windows_folder_separator_listFiles_detects_wrong_pattern(){
```
Comment (andrei-epure-sonarsource) [inline sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/WildcardPatternFileProviderTest.java:240]: the pattern is with mixed folder separators, right? Because `tmpRoot` and `FileSeparator` will be Windows, and `_temp/**/*.trx` are UNIX?

and rather than "detects", it should be "supports", because from the test I cannot see the detection itself (there's no message "Pattern detected")

File: its/src/test/java/com/sonar/it/csharp/CoverageTest.java [hunk 3]
```diff
@@ -101,6 +101,18 @@ public void open_cover_on_MultipleProjects() throws Exception {
     assertCoverageMetrics("MultipleProjects:SecondProject/FirstClass.cs", 11, 3, 10, 4);
   }
 
+  @Test
+  public void open_cover_on_MultipleProjects_with_wildcardPattern() throws Exception {
```
Comment (andrei-epure-sonarsource) [inline its/src/test/java/com/sonar/it/csharp/CoverageTest.java:105]: maybe improve and mention `with_UnixWildcardPattern` ?

File: its/src/test/java/com/sonar/it/csharp/CoverageTest.java [hunk 4]
```diff
@@ -101,6 +101,18 @@ public void open_cover_on_MultipleProjects() throws Exception {
...
+    BuildResult buildResult = analyzeMultipleProjectsTestProject("sonar.cs.opencover.reportsPaths", "/*/opencover.xml");
+
+    // The original opencover is moved to a subfolder and parts of it are removed and that is how we know the correct one is matched.
```
Comment (andrei-epure-sonarsource) [inline its/src/test/java/com/sonar/it/csharp/CoverageTest.java:108]: nice!

File: its/projects/MultipleProjects/WildcardPatternTest/opencover.xml [hunk 5]
```diff
@@ -0,0 +1,1520 @@
+<?xml version="1.0" encoding="utf-8"?>
```
Comment (andrei-epure-sonarsource) [inline its/projects/MultipleProjects/WildcardPatternTest/opencover.xml:1]: maybe mention in a comment how you modified this file, and which is the source? 

You'll need to put the comment after the `<?xml` tag for it to be valid XML, as far as I remember

see [this example](https://github.com/SonarSource/sonar-dotnet/blob/master/its/projects/CoverageWithDeterministicSourcePaths/opencover.xml#L2)

**Review by andrei-epure-sonarsource — CHANGES_REQUESTED** [review]
nice, I have some suggestions

File: sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/WildcardPatternFileProviderTest.java [hunk 6]
```diff
@@ -237,7 +237,7 @@ public void should_fail_with_parent_folder_access_after_wildcard() {
   }
 
   @Test
-  public void given_pattern_with_windows_folder_separator_listFiles_detects_wrong_pattern(){
+  public void given_pattern_with_mixed_folder_separator_and_UnixWildcard_listFiles_supports_pattern(){
```
Comment (andrei-epure-sonarsource) [inline sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/WildcardPatternFileProviderTest.java:240]: I think you copy pasted the UnixWildcard idea from the comment I made on `CoverageTest.java`...

if you put "mixed_folder_separator", you don't need the `UnixWildcard`, right?

**Review by andrei-epure-sonarsource — APPROVED** [review]
LGTM, please note you haven't addressed my initial comment on `CoverageTest.java` , and I left another one on

File: its/src/test/java/com/sonar/it/csharp/CoverageTest.java (hunk 3 above)
Comment (andrei-epure-sonarsource) [reply its/src/test/java/com/sonar/it/csharp/CoverageTest.java:105]: this hasn't been addressed

**Comment by andrei-epure-sonarsource** [comment]
Also, please check the code smell as it's related to the performance of the regex: https://sonarcloud.io/project/issues?id=org.sonarsource.dotnet%3Asonar-dotnet&open=AXf4EY9bL2-FIDEPQJ15&pullRequest=4103&resolved=false&types=CODE_SMELL

File: sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/WildcardPatternFileProviderTest.java (hunk 6 above)
Comment (csaba-sagi-sonarsource) [reply sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/WildcardPatternFileProviderTest.java:240]: I accidentally merged two of your comments :)

**Comment by andrei-epure-sonarsource** [comment]
UTs are failing due to the problem mentioned in #4115
