### PR TITLE
Fix S1172 FP: Should not raise for event handlers

### LINKED ISSUE #4406: Fix S1172 FP: Should not raise for event handlers
### Description

S1172 raises issue to remove parameters from event handlers where the method signature cannot be changed.

It should not apply to methods with `Handles Source.Event` syntax.

### Repro steps

```
Public Class Source

    Public Event Dirty(Sender As Object, Name As String, Count As Integer)

End Class

Public Class Consumer

    Private WithEvents fSource As Source

    Private Sub fSource_Dirty(Sender As Object, Name As String, Count As Integer) Handles fSource.Dirty 'FP
        Dim S As String = Name
    End Sub

End Class
```

### PR DESCRIPTION
**Pull request by pavel-mikula-sonarsource**
Fixes #4406

### CODE REVIEW

File: analyzers/src/SonarAnalyzer.VisualBasic/Rules/MethodParameterUnused.cs [hunk 1]
```diff
@@ -66,92 +63,71 @@ protected override void Initialize(SonarAnalysisContext context)
...
         private static bool HasAnyAttribute(MethodBlockBaseSyntax method) =>
-            method.BlockStatement.AttributeLists.Count > 0;
+            method.BlockStatement.AttributeLists.Any();
 
         private static bool OnlyThrowsNotImplementedException(MethodBlockBaseSyntax method, SemanticModel semanticModel) =>
             method.Statements.Count == 1
             && method.Statements
                 .OfType<ThrowStatementSyntax>()
-                .Select(tss => tss.Expression)
+                .Select(x => x.Expression)
```
Comment (andrei-epure-sonarsource) [inline analyzers/src/SonarAnalyzer.VisualBasic/Rules/MethodParameterUnused.cs:108]: yes here `x` is much better than `tss`, `oces` or `s` :)

File: analyzers/src/SonarAnalyzer.VisualBasic/Rules/MethodParameterUnused.cs [hunk 2]
```diff
@@ -67,7 +67,6 @@ public sealed class MethodParameterUnused : MethodParameterUnusedBase
                     // Bail-out if this is not a method we want to report on (only based on symbols checks)
                     var methodSymbol = c.SemanticModel.GetDeclaredSymbol(methodBlock);
                     if (methodSymbol == null
-                        || methodSymbol.IsAbstract
```
Comment (andrei-epure-sonarsource) [inline analyzers/src/SonarAnalyzer.VisualBasic/Rules/MethodParameterUnused.cs]: this seems like a change in bevahior? is it intended? shouldn't a test be added for abstract methods?

**Review by andrei-epure-sonarsource — CHANGES_REQUESTED** [review]

File: analyzers/src/SonarAnalyzer.VisualBasic/Rules/MethodParameterUnused.cs (hunk 2 above)
Comment (pavel-mikula-sonarsource) [reply analyzers/src/SonarAnalyzer.VisualBasic/Rules/MethodParameterUnused.cs]: It's for coverage. This condition is unreachable because of syntax checks above. And there's case in UTs for it as well (`MustOverride`).

File: analyzers/src/SonarAnalyzer.VisualBasic/Rules/MethodParameterUnused.cs (hunk 1 above)
Comment (pavel-mikula-sonarsource) [reply analyzers/src/SonarAnalyzer.VisualBasic/Rules/MethodParameterUnused.cs:108]: I found `oces` especially hard to understand. Even when it became obvious when you finally find it :)

**Review by andrei-epure-sonarsource — APPROVED** [review]
LGTM
