### PR TITLE
Analyze projects with no sources

### LINKED ISSUE #3600: Fix the S4MSB property detection error that surfaced in security
See this[ cirrus ci failed job ](https://cirrus-ci.com/task/5701631268356096?command=qa_csharp_msbuild16#L2850)

```
INFO: ------------- Run sensors on project
INFO: Sensor C# [csharp]
...
ERROR: Error during SonarQube Scanner execution
ERROR: No Roslyn issue reports were found.
```

After this gets merged, we need to use again `DEV` version in the security ITs instead of `LATEST_RELEASE` and test all security ITs work as expected.

Only after then we can release.

### PR DESCRIPTION
**Pull request by andrei-epure-sonarsource**
Fixes #3600

### CODE REVIEW

File: its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+
+    ORCHESTRATOR.executeBuild(beginStep);
+
+    TestUtils.runMSBuild(ORCHESTRATOR, projectDir, "/t:Rebuild");
+
+    ORCHESTRATOR.executeBuild(TestUtils.createEndStep(projectDir));
+  }
+
+  @Test
+  public void filesAtProjectLevel() {
```
Comment (andrei-epure-sonarsource) [inline its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java:41]: I cherry-picked this on `master` and it fails with the `No Roslyn issue reports were found.`

File: its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java [hunk 2]
```diff
@@ -0,0 +1,50 @@
+package com.sonar.it.csharp;
```
Comment (pavel-mikula-sonarsource) [inline its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java:1]: Java ITs failed on missing licence header in this file

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractModuleConfiguration.java [hunk 3]
```diff
@@ -58,10 +58,14 @@
 
   private final Configuration configuration;
   private final String languageKey;
+  // we store the project key for logging
```
Comment (pavel-mikula-sonarsource) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractModuleConfiguration.java:61]: I think we can remove this comment. It's clearly visible from usages.

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractModuleConfiguration.java [hunk 4]
```diff
@@ -81,51 +85,51 @@ static String getAnalyzerReportDir(String languageKey) {
...
+      return Arrays.stream(strPaths)
+        .map(Paths::get)
+        .collect(Collectors.toList());
+    } else {
+      LOG.warn( "For project '{}', no Roslyn issues reports have been found.", projectKey);
+      return Collections.emptyList();
+    }
+  }
+
+  private static boolean validateOutputDir(Path analyzerOutputDir, String projectKey) {
```
Comment (pavel-mikula-sonarsource) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractModuleConfiguration.java:109]: The passing of class state into static method seems painful and non-natural. Can you remove the `static` instead to simplify the call site to original form and the state management?

```suggestion
  private boolean validateOutputDir(Path analyzerOutputDir) {
```

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractModuleConfiguration.java [hunk 5]
```diff
@@ -81,51 +85,51 @@ static String getAnalyzerReportDir(String languageKey) {
...
     String path = analyzerOutputDir.toString();
     try {
       if (!analyzerOutputDir.toFile().exists()) {
-        LOG.warn("Analyzer working directory does not exist: '{}'. {}", path, MSG_SUFFIX);
+        LOG.warn("For project '{}', analyzer working directory does not exist: '{}'. {}", projectKey, path, MSG_SUFFIX);
```
Comment (pavel-mikula-sonarsource) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractModuleConfiguration.java:113]: I like the idea of having unified prefix in all messages. To avoid fight with English language, I'd use this technical form to avoid the problem:
```suggestion
        LOG.warn("Project '{}': Analyzer working directory does not exist '{}'. {}", projectKey, path, MSG_SUFFIX);
```

File: sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/AbstractModuleConfigurationTest.java [hunk 6]
```diff
@@ -67,7 +67,7 @@ public void giveWarningsWhenGettingProtobufPathAndNoPropertyAvailable() {
 
     AbstractModuleConfiguration config = createAbstractModuleConfiguration(configuration);
     assertThat(config.protobufReportPaths()).isEmpty();
-    assertThat(logTester.logs(LoggerLevel.WARN)).containsOnly("Property missing: 'sonar.cs.analyzer.projectOutPaths'. No protobuf files will be loaded for this project.");
+    assertThat(logTester.logs(LoggerLevel.WARN)).containsOnly("Property missing: 'sonar.cs.analyzer.projectOutPaths'. No protobuf files will be loaded for project '<NONE>'.");
```
Comment (pavel-mikula-sonarsource) [inline sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/AbstractModuleConfigurationTest.java:70]: Can you change mocking of this test to use some project key to see that the value is really used? The `<NONE>` is tested by the test below.

File: its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java [hunk 7]
```diff
@@ -0,0 +1,50 @@
...
+import org.junit.BeforeClass;
+import org.junit.ClassRule;
+import org.junit.Test;
+import org.junit.rules.TemporaryFolder;
+
+import static com.sonar.it.csharp.Tests.ORCHESTRATOR;
+import static com.sonar.it.csharp.Tests.getMeasureAsInt;
+import static org.assertj.core.api.Assertions.assertThat;
+
+public class NoSourcesTest {
```
Comment (pavel-mikula-sonarsource) [inline its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java:16]: This should be registered in `its/src/test/java/com/sonar/it/csharp/Tests.java` AFAIK

File: its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java [hunk 8]
```diff
@@ -0,0 +1,50 @@
...
+
+  private static final String PROJECT = "ProjectWithNoSources";
+  @ClassRule
+  public static final Orchestrator orchestrator = Tests.ORCHESTRATOR;
+
+  @BeforeClass
+  public static void init() throws Exception {
+    TestUtils.reset(orchestrator);
+
+    Path projectDir = Tests.projectDir(temp, "ProjectWithNoSources");
```
Comment (pavel-mikula-sonarsource) [inline its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java:29]: The constant `PROJECT` should be used here and below

File: its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java [hunk 9]
```diff
@@ -0,0 +1,50 @@
...
+import org.junit.rules.TemporaryFolder;
+
+import static com.sonar.it.csharp.Tests.ORCHESTRATOR;
+import static com.sonar.it.csharp.Tests.getMeasureAsInt;
+import static org.assertj.core.api.Assertions.assertThat;
+
+public class NoSourcesTest {
+
+  @ClassRule
+  public static TemporaryFolder temp = TestUtils.createTempFolder();
```
Comment (pavel-mikula-sonarsource) [inline its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java:19]: _CodeSmell:_
```suggestion
  public static final TemporaryFolder temp = TestUtils.createTempFolder();
```

File: its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java [hunk 10]
```diff
@@ -0,0 +1,50 @@
...
+  }
+
+  @Test
+  public void filesAtProjectLevel() {
+    assertThat(getProjectMeasureAsInt("violations")).isEqualTo(4);
+  }
+
+  /* Helper methods */
+
+  private Integer getProjectMeasureAsInt(String metricKey) {
```
Comment (pavel-mikula-sonarsource) [inline its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java:47]: This is copy/pasted all over the place 7 times. Can you refactor it to some `TestHelper` class?

File: its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java (hunk 8 above)
Comment (pavel-mikula-sonarsource) [inline its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java:29]: This initialization seems to be copy/pasted several times, can it be factored out to some `TestHelper` class?
To clarify: Only for simple cases with single `projectDir` argument.

File: its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java [hunk 11]
```diff
@@ -0,0 +1,50 @@
...
+import static com.sonar.it.csharp.Tests.ORCHESTRATOR;
+import static com.sonar.it.csharp.Tests.getMeasureAsInt;
+import static org.assertj.core.api.Assertions.assertThat;
+
+public class NoSourcesTest {
+
+  @ClassRule
+  public static TemporaryFolder temp = TestUtils.createTempFolder();
+
+  private static final String PROJECT = "ProjectWithNoSources";
```
Comment (pavel-mikula-sonarsource) [inline its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java:21]: I'd prefer to have those two `@ClassRule` together and this constant above/below them. Current order and empty lines seems irregular.

**Review by pavel-mikula-sonarsource — CHANGES_REQUESTED** [review]

File: its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java (hunk 2 above)
Comment (andrei-epure-sonarsource) [reply its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java:1]: Indeed,Ionly ranit in theide

File: its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java (hunk 10 above)
Comment (andrei-epure-sonarsource) [reply its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java:47]: `getMeasureAsInt` is already a helper. The `getProjectMeasureAsInt` is copy/pasted to avoid having `getMeasureAsInt(PROJECT, metricKey);` all over the tests and simply call `getProjectMeasureAsInt("lines")`

however in such a simple test it's an overkill, so I will call directly `getMeasureAsInt`

File: its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java (hunk 8 above)
Comment (andrei-epure-sonarsource) [reply its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java:29]: well, the `temp` needs to be passed from here as it's `ClassRule` annotated; and the projectDir needs to be passed... 

it's already in the `TestHelper`. 

Do you mean initializing _and_ doing the analysis? I think the way it is now makes the test understandable, each step

Comment (pavel-mikula-sonarsource) [reply its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java:29]: It still makes sense to factor it to a separate method with 3 args. Because it can be reused several times all over the place.
The test itself is readable, but the big picture copy/paste/duplication is not a great pattern to maintain.

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractModuleConfiguration.java [hunk 12]
```diff
@@ -85,43 +84,43 @@ static String getAnalyzerReportDir(String languageKey) {
...
     return analyzerWorkDirPaths.stream().map(x -> x.resolve(getAnalyzerReportDir(languageKey)))
-      .filter(dir -> validateOutputDir(dir, projectKey))
+      .filter(this::validateOutputDir)
       .collect(Collectors.toList());
   }
 
   public List<Path> roslynReportPaths() {
     String[] strPaths = configuration.getStringArray(getRoslynJsonReportPathProperty(languageKey));
-    LOG.debug("For project '{}', the Roslyn JSON report path has '{}'", projectKey, String.join(",", strPaths));
+    LOG.debug("Project '{}': The Roslyn JSON report path has '{}'", projectKey, String.join(",", strPaths));
```
Comment (andrei-epure-sonarsource) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractModuleConfiguration.java:97]: I want to add more UTs for the comments, but it will be a small update

File: its/src/test/java/com/sonar/it/csharp/MetricsTest.java [hunk 13]
```diff
@@ -292,18 +280,10 @@ public void executableLines() {
 
   /* Helper methods */
 
-  private Measure getProjectMeasure(String metricKey) {
```
Comment (andrei-epure-sonarsource) [inline its/src/test/java/com/sonar/it/csharp/MetricsTest.java:295]: these weren't used

File: its/src/test/java/com/sonar/it/csharp/DoNotAnalyzeTestFilesTest.java [hunk 14]
```diff
@@ -37,31 +36,30 @@
...
   @Before
   public void init() {
-    TestUtils.reset(orchestrator);
+    TestUtils.reset(ORCHESTRATOR);
   }
 
   @Test
   public void should_not_increment_test() throws Exception {
-    Path projectDir = Tests.projectDir(temp, "DoNotAnalyzeTestFilesTest");
+    Path projectDir = Tests.projectDir(temp, PROJECT);
```
Comment (pavel-mikula-sonarsource) [inline its/src/test/java/com/sonar/it/csharp/DoNotAnalyzeTestFilesTest.java:48]: Nice cleanup 👍

File: its/src/test/java/com/sonar/it/csharp/MetricsTest.java [hunk 15]
```diff
@@ -59,26 +59,14 @@ private static RuleChain getRuleChain() {
         @Override
         protected void before() throws Throwable {
           TestUtils.reset(ORCHESTRATOR);
-
-          Path projectDir = Tests.projectDir(temp, "MetricsTest");
-
-          ScannerForMSBuild beginStep = TestUtils.createBeginStep("MetricsTest", projectDir)
-            .setProfile("no_rule")
-            // Without that, the MetricsTest project is considered as a Test project :)
```
Comment (pavel-mikula-sonarsource) [inline its/src/test/java/com/sonar/it/csharp/MetricsTest.java:67]: Can you preserve this comment? I find it useful. Similar one is in `NoSonarTest.java`

File: its/src/test/java/com/sonar/it/csharp/SharedFilesTest.java [hunk 16]
```diff
@@ -40,26 +37,14 @@
...
 
-  @ClassRule
-  public static final Orchestrator orchestrator = Tests.ORCHESTRATOR;
-
   @Before
-  public void init() {
-    TestUtils.reset(orchestrator);
+  public void init(){
+    TestUtils.reset(ORCHESTRATOR);
   }
```
Comment (pavel-mikula-sonarsource) [inline its/src/test/java/com/sonar/it/csharp/SharedFilesTest.java:44]: _Nitpick:_ 44 and 57 has some whitespace

File: its/src/test/java/com/sonar/it/csharp/Tests.java [hunk 17]
```diff
@@ -83,6 +87,20 @@ public static Path projectDir(TemporaryFolder temp, String projectName) throws I
     return tmpProjectDir;
   }
 
+  static BuildResult analyzeProject(TemporaryFolder temp, String projectName, @Nullable String profileKey, String... keyValues) throws IOException {
```
Comment (pavel-mikula-sonarsource) [inline its/src/test/java/com/sonar/it/csharp/Tests.java:90]: _Optionally:_ Can you add second method with almost the same content with extra subProjectName argument and `TestUtils.createBeginStep(projectName, projectDir, subProjectName)`? That should simplify almost all of the rest of the invocations.

File: its/src/test/java/com/sonar/it/vbnet/MetricsTest.java [hunk 18]
```diff
@@ -55,26 +56,14 @@ private static RuleChain getRuleChain() {
         @Override
         protected void before() throws Throwable {
           TestUtils.reset(ORCHESTRATOR);
-
-          Path projectDir = Tests.projectDir(temp, "VbMetricsTest");
-
-          ScannerForMSBuild beginStep = TestUtils.createBeginStep("VbMetricsTest", projectDir)
-            .setProfile("vbnet_no_rule")
-            // Without that, the MetricsTest project is considered as a Test project :)
```
Comment (pavel-mikula-sonarsource) [inline its/src/test/java/com/sonar/it/vbnet/MetricsTest.java:63]: Can this comment be preserved? I find it useful.

File: its/src/test/java/com/sonar/it/vbnet/NoSonarTest.java [hunk 19]
```diff
@@ -36,37 +36,21 @@
...
 
   @BeforeClass
   public static void init() throws Exception {
     TestUtils.reset(orchestrator);
-
-    Path projectDir = Tests.projectDir(temp, "VbNoSonarTest");
-
-    ScannerForMSBuild beginStep = TestUtils.createBeginStep("VbNoSonarTest", projectDir)
-      .setProfile("vbnet_class_name")
-      // Without that, the NoSonarTest project is considered as a Test project :)
```
Comment (pavel-mikula-sonarsource) [inline its/src/test/java/com/sonar/it/vbnet/NoSonarTest.java:51]: Same here

**Review by pavel-mikula-sonarsource — APPROVED** [review]
LGTM! Nice work and cleanup

File: its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java (hunk 8 above)
Comment (pavel-mikula-sonarsource) [reply its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java]: Awesome!

**Comment by andrei-epure-sonarsource** [comment]
moving this to draft as we have warnings on non-C# builds (e.g. Java build)
from analyzing sonar-java

```
[INFO] Sensor C# Properties [csharp]
[WARNING] Project 'org.sonarsource.java:it-java-semantic': Property missing: 'sonar.cs.analyzer.projectOutPaths'. No protobuf files will be loaded for this project.
[WARNING] Project 'org.sonarsource.java:it-java-semantic': No Roslyn issues reports have been found.
[INFO] Sensor C# Properties [csharp] (done) | time=28ms
```

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/DotNetSensor.java [hunk 20]
```diff
@@ -91,6 +91,8 @@ private void executeInternal(SensorContext context) {
     List<Path> protobufPaths = reportPathCollector.protobufDirs();
     if (!protobufPaths.isEmpty()) {
       protobufDataImporter.importResults(context, protobufPaths, toRealPath);
+    } else {
+      LOG.warn("No protobuf reports found - no metrics and highlighting will be imported.");
```
Comment (andrei-epure-sonarsource) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/DotNetSensor.java:95]: @pavel-mikula-sonarsource  given that we fail if no roslyn reports are found... shouldn't we also (or even the more) fail if no highlighting can be made?

**Comment by andrei-epure-sonarsource** [comment]
Another scenario to manually test before the release of 8,13: what if a CS file is referenced for some reason in the sources of a maven build?

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/DotNetSensor.java (hunk 20 above)
Comment (pavel-mikula-sonarsource) [reply sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/DotNetSensor.java:95]: I don't think so, I've chosen only the Roslyn property to fail fast because of this comment:
https://github.com/SonarSource/sonar-dotnet/blob/ee3a8953dacbde39b0ff18c86d04cb95724cd8a5/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractModuleConfiguration.java#L82

Having "SQ Project" containing only .NET test project and maybe some other non-.NET stuff you'd like to analyze is (weird but) legal setup with Roslyn in place and should be analyzed. This might change once `Tests as 1st class citizen` is done and we modify the pb generation and that comment.

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/DotNetSensor.java [hunk 21]
```diff
@@ -91,6 +91,8 @@ private void executeInternal(SensorContext context) {
     List<Path> protobufPaths = reportPathCollector.protobufDirs();
     if (!protobufPaths.isEmpty()) {
```
Comment (pavel-mikula-sonarsource) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/DotNetSensor.java:92]: Can you please swap this condition to have a positive test?
```suggestion
    if (protobufPaths.isEmpty()) {
```

**Review by pavel-mikula-sonarsource — APPROVED** [review]
Still LGTM with one minor suggestion
