### PR TITLE
Rule S2302: Get rid of noisy FP

### LINKED ISSUE #4454: Fix S2302 FP: Rule should be less sensitive for message of Argument exceptions
### Description

S2302 should be less sensitive to message inside ArgumentException, ArgumentNullException, ArgumentOutOfRangeException

### Repro steps

```
            throw new ArgumentException("This is argument."); // Noncompliant
            throw new ArgumentException("This is argument.", nameof(argument)); // Noncompliant FP
            throw new ArgumentException("argument and arg1"); // Noncompliant
            throw new ArgumentException("argument and arg1", nameof(arg1)); // Noncompliant FP
            throw new ArgumentNullException(nameof(argument), "Incorrect argument value"); // Noncompliant FP
            throw new ArgumentOutOfRangeException(nameof(argument), "Incorrect argument value"); // Noncompliant FP
            throw new ArgumentOutOfRangeException(nameof(argument), argument, "Incorrect argument value"); // Noncompliant FP
```

### Expected behavior

Issue should not be raised in the cases above.

### Actual behavior

Issue is being raised.

### Related information

* C#/VB.NET Plugins version 8.22

### PR DESCRIPTION
**Pull request by dmitry-golovinov-sonarsource**
Fixes #4454

### CODE REVIEW

File: analyzers/src/SonarAnalyzer.VisualBasic/Rules/NameOfShouldBeUsed.cs [hunk 1]
```diff
@@ -66,6 +66,20 @@ protected override IEnumerable<string> GetParameterNames(MethodBlockBaseSyntax m
...
 
+        protected override bool IsArgumentExceptionCallingNameOf(SyntaxNode node, IEnumerable<string> arguments)
+        {
+            var throwNode = (ThrowStatementSyntax)node;
+            if (throwNode.Expression is ObjectCreationExpressionSyntax objectCreation)
+            {
+                var nameOfCallIdx = objectCreation.ArgumentList.Arguments.IndexOf(x =>
+                    x.GetExpression() is NameOfExpressionSyntax nameOfExpression
+                    && arguments.Contains(nameOfExpression.Argument.ToString()));
+                return ArgumentExceptionCouldBeSkipped(objectCreation.Type.ToString(), nameOfCallIdx);
```
[the remark this answers is not in the document]
Comment (dmitry-golovinov-sonarsource) [reply analyzers/src/SonarAnalyzer.VisualBasic/Rules/NameOfShouldBeUsed.cs:77]: This is not a FP. If nameof stays as a second argument here - dev knows what he does and the issue won't be raised.

[the remark this answers is not in the document]
Comment (csaba-sagi-sonarsource) [reply analyzers/src/SonarAnalyzer.VisualBasic/Rules/NameOfShouldBeUsed.cs:68]: I agree that it is a very rare case, and I understand if you do not want to tackle it, and I would still like to have at least the case documented, as the rule suggests to change the "argument" to `nameof(argument)` in this case which is the opposite of what the rule should do.

[the remark this answers is not in the document]
Comment (dmitry-golovinov-sonarsource) [reply analyzers/src/SonarAnalyzer.VisualBasic/Rules/NameOfShouldBeUsed.cs:68]: Ok, will do with the next review round

File: analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NameOfShouldBeUsed.cs [hunk 2]
```diff
@@ -37,23 +37,27 @@ public void Method_01(int arg1, int argument)
...
-            throw new ArgumentOutOfRangeException(nameof(argument), "argument"); // Noncompliant
-            throw new ArgumentOutOfRangeException(nameof(argument), "Incorrect argument value"); // Noncompliant FP
-            throw new ArgumentOutOfRangeException(nameof(argument), argument, "argument"); // Noncompliant
-            throw new ArgumentOutOfRangeException(nameof(argument), argument, "Incorrect argument value"); // Noncompliant FP
+            throw new ArgumentOutOfRangeException(nameof(argument), "argument");
+            throw new ArgumentOutOfRangeException(nameof(argument), "Incorrect argument value");
+            throw new ArgumentOutOfRangeException(nameof(argument), argument, "argument");
+            throw new ArgumentOutOfRangeException(nameof(argument), argument, "Incorrect argument value");
+
+            var ex1 = new ArgumentException("This is argument."); // Compliant FN
```
Comment (csaba-sagi-sonarsource) [inline analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NameOfShouldBeUsed.cs:57]: NITPICK: The comment should be either Compliant or FN. Same for the VBNET example.

File: analyzers/src/SonarAnalyzer.CSharp/Rules/NameOfShouldBeUsed.cs [hunk 3]
```diff
@@ -33,53 +32,45 @@ namespace SonarAnalyzer.Rules.CSharp
...
 
         protected override IEnumerable<string> GetParameterNames(BaseMethodDeclarationSyntax method)
         {
-            var paramGroups = method.ParameterList?.Parameters
-                .GroupBy(p => p.Identifier.ValueText);
-
-            if (paramGroups != null &&
-                paramGroups.Any(g => g.Count() != 1))
+            var paramGroups = method.ParameterList?.Parameters.GroupBy(p => p.Identifier.ValueText);
+            if (paramGroups != null && paramGroups.Any(g => g.Count() != 1))
```
Comment (csaba-sagi-sonarsource) [inline analyzers/src/SonarAnalyzer.CSharp/Rules/NameOfShouldBeUsed.cs:50]: Something is not OK here, if paramGroups is null, we will have a null reference exception.

File: analyzers/src/SonarAnalyzer.CSharp/Rules/NameOfShouldBeUsed.cs [hunk 4]
```diff
@@ -33,53 +32,45 @@ namespace SonarAnalyzer.Rules.CSharp
...
     [DiagnosticAnalyzer(LanguageNames.CSharp)]
     [Rule(DiagnosticId)]
-    public sealed class NameOfShouldBeUsed : NameOfShouldBeUsedBase<BaseMethodDeclarationSyntax>
+    public sealed class NameOfShouldBeUsed : NameOfShouldBeUsedBase<BaseMethodDeclarationSyntax, SyntaxKind, ThrowStatementSyntax>
     {
-       private static readonly HashSet<SyntaxKind> StringTokenTypes
-            = new HashSet<SyntaxKind>
+        private static readonly HashSet<SyntaxKind> StringTokenTypes = new HashSet<SyntaxKind>
             {
                 SyntaxKind.InterpolatedStringTextToken,
```
Comment (csaba-sagi-sonarsource) [inline analyzers/src/SonarAnalyzer.CSharp/Rules/NameOfShouldBeUsed.cs:39]: NITPICK: Indented.

File: analyzers/src/SonarAnalyzer.VisualBasic/Rules/NameOfShouldBeUsed.cs [hunk 5]
```diff
@@ -32,56 +31,44 @@ namespace SonarAnalyzer.Rules.VisualBasic
 {
     [DiagnosticAnalyzer(LanguageNames.VisualBasic)]
     [Rule(DiagnosticId)]
-    public sealed class NameOfShouldBeUsed : NameOfShouldBeUsedBase<MethodBlockBaseSyntax>
+    public sealed class NameOfShouldBeUsed : NameOfShouldBeUsedBase<MethodBlockBaseSyntax, SyntaxKind, ThrowStatementSyntax>
     {
-        private static readonly HashSet<SyntaxKind> StringTokenTypes
-            = new HashSet<SyntaxKind>
+        private static readonly HashSet<SyntaxKind> StringTokenTypes = new HashSet<SyntaxKind>
             {
```
Comment (csaba-sagi-sonarsource) [inline analyzers/src/SonarAnalyzer.VisualBasic/Rules/NameOfShouldBeUsed.cs:37]: NITPICK: Same as for the C# version. No need for indenting.

File: analyzers/src/SonarAnalyzer.Common/Rules/NameOfShouldBeUsedBase.cs [hunk 6]
```diff
@@ -18,49 +18,76 @@
...
+using Microsoft.CodeAnalysis;
+using Microsoft.CodeAnalysis.Diagnostics;
+using SonarAnalyzer.Helpers;
 
 namespace SonarAnalyzer.Rules
 {
-    public abstract class NameOfShouldBeUsedBase : SonarDiagnosticAnalyzer
+    public abstract class NameOfShouldBeUsedBase<TMethodSyntax, TSyntaxKind, TThrowSyntax> : SonarDiagnosticAnalyzer
+            where TMethodSyntax : SyntaxNode
+            where TSyntaxKind : struct
```
Comment (csaba-sagi-sonarsource) [inline analyzers/src/SonarAnalyzer.Common/Rules/NameOfShouldBeUsedBase.cs:33]: NITPICK: Should have only 1 tab of indenting.

File: analyzers/src/SonarAnalyzer.Common/Rules/NameOfShouldBeUsedBase.cs [hunk 7]
```diff
@@ -18,49 +18,76 @@
...
+        private readonly DiagnosticDescriptor rule;
 
-        protected abstract bool IsCaseSensitive { get; }
+        protected abstract ILanguageFacade<TSyntaxKind> Language { get; }
 
-        protected StringComparison CaseSensitivity
-        {
-            get => IsCaseSensitive ? StringComparison.InvariantCulture : StringComparison.InvariantCultureIgnoreCase;
-        }
+        public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => ImmutableArray.Create(rule);
```
Comment (csaba-sagi-sonarsource) [inline analyzers/src/SonarAnalyzer.Common/Rules/NameOfShouldBeUsedBase.cs:47]: Should go after the abstract members.

File: analyzers/src/SonarAnalyzer.Common/Rules/NameOfShouldBeUsedBase.cs [hunk 8]
```diff
@@ -82,9 +110,9 @@ protected void ReportIssues<TThrowSyntax>(SyntaxNodeAnalysisContext context)
             }
         }
 
-        protected void ReportIssue(SyntaxToken stringLiteralToken, string parameterName, SyntaxNodeAnalysisContext context) =>
+        private void ReportIssue(SyntaxToken stringLiteralToken, string parameterName, SyntaxNodeAnalysisContext context) =>
```
Comment (csaba-sagi-sonarsource) [inline analyzers/src/SonarAnalyzer.Common/Rules/NameOfShouldBeUsedBase.cs:113]: I am not convinced that we need this method, as it is called only in one place.

File: analyzers/src/SonarAnalyzer.Common/Rules/NameOfShouldBeUsedBase.cs [hunk 9]
```diff
@@ -18,49 +18,76 @@
  * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
```
Comment (csaba-sagi-sonarsource) [inline analyzers/src/SonarAnalyzer.Common/Rules/NameOfShouldBeUsedBase.cs:18]: At least for me the file has an unnecessary new line at the end of the file.

File: analyzers/src/SonarAnalyzer.CSharp/Rules/NameOfShouldBeUsed.cs (hunk 3 above)
Comment (dmitry-golovinov-sonarsource) [reply analyzers/src/SonarAnalyzer.CSharp/Rules/NameOfShouldBeUsed.cs:50]: Wow, you've spotted an old error. Thanks for the catch! But I am not sure that we could reproduce that, since parameter list is non-empty always (otherwise AST regards it as property)

File: analyzers/src/SonarAnalyzer.Common/Rules/NameOfShouldBeUsedBase.cs (hunk 7 above)
Comment (dmitry-golovinov-sonarsource) [reply analyzers/src/SonarAnalyzer.Common/Rules/NameOfShouldBeUsedBase.cs:47]: Indeed!

File: analyzers/src/SonarAnalyzer.VisualBasic/Rules/NameOfShouldBeUsed.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (dmitry-golovinov-sonarsource) [reply analyzers/src/SonarAnalyzer.VisualBasic/Rules/NameOfShouldBeUsed.cs:68]: The logic was fixed and this is no longer a FP

**Review by csaba-sagi-sonarsource — APPROVED** [review]
LGTM!
