### PR TITLE
Fix RegEx hotspots in DotCoverReportParser

### LINKED ISSUE #4194: Fix RegEx hotspots in DotCoverReportParser
Remove backtracking from Regex in `DotCoverReportParser`, as found on SonarCloud:
https://sonarcloud.io/project/security_hotspots?id=org.sonarsource.dotnet%3Asonar-dotnet&sinceLeakPeriod=true#

```
private static final Pattern TITLE_PATTERN = Pattern.compile(".*?<title>(.*?)</title>.*", Pattern.DOTALL);
private static final Pattern COVERED_LINES_PATTERN_1 = Pattern.compile(
    ".*<script type=\"text/javascript\">\\s*+highlightRanges\\(\\[(.*?)\\]\\);\\s*+</script>.*",
    Pattern.DOTALL);
```

### PR DESCRIPTION
**Pull request by andrei-epure-sonarsource**
Fixes #4194

### CODE REVIEW

File: sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java [hunk 1]
```diff
@@ -31,9 +31,8 @@
 
 public class DotCoverReportParser implements CoverageParser {
 
-  private static final Pattern TITLE_PATTERN = Pattern.compile(".*?<title>(.*?)</title>.*", Pattern.DOTALL);
   private static final Pattern COVERED_LINES_PATTERN_1 = Pattern.compile(
-    ".*<script type=\"text/javascript\">\\s*+highlightRanges\\(\\[(.*?)\\]\\);\\s*+</script>.*",
+    ".*<script type=\"text/javascript\">\\s*+highlightRanges\\(\\[([\\d\\[\\],]*?)\\]\\);\\s*+</script>.*",
```
[the remark this answers is not in the document]
Comment (pavel-mikula-sonarsource) [reply sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java:35]: TBH I don't understand the purpose of `COVERED_LINES_PATTERN_1` and `COVERED_LINES_PATTERN_2`, better naming could help. But the v2 seems prettly similar to what my `FRAGMENT` does.

**Review by pavel-mikula-sonarsource — CHANGES_REQUESTED** [review]
Some improvements suggested

File: sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java [hunk 2]
```diff
@@ -32,10 +32,14 @@
 public class DotCoverReportParser implements CoverageParser {
 
   private static final String TITLE_START = "<title>";
+  // the pattern for the information about a sequence point - (lineStart, columnStart, lineEnd, columnEnd, hits)
+  private static final Pattern SEQUENCE_POINT_PATTERN = Pattern.compile("\\[(\\d++),\\d++,(\\d++),\\d++,(\\d++)]");
```
Comment (andrei-epure-sonarsource) [inline sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java:36]: I realize now that we don't really use the 2nd captured number - it's lineEnd but we don't use it

File: sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java [hunk 3]
```diff
@@ -93,27 +96,39 @@ private String extractFileCanonicalPath(String contents) {
...
 
         coverage.addHits(fileCanonicalPath, lineStart, hits);
 
         LOG.trace("dotCover parser: found coverage for line '{}', hits '{}' when analyzing the path '{}'.",
-            lineStart, hits, fileCanonicalPath);
+          lineStart, hits, fileCanonicalPath);
+      }
+    }
+
+    private int getIndexOf(String fileContent, String tag) {
```
Comment (pavel-mikula-sonarsource) [inline sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java:118]: We could use `public int indexOf(String str, int fromIndex)` overload.
It will start from 0 for the `<title>`
It will start from `<title>` to search for `</title>`, ensuring we have consistent state.

Like this, we can remove `getTitlePath`, as the check will be naturally embedded in the system.
```suggestion
    private int getIndexOf(String fileContent, String tag, int startIndex = 0) {
```

File: sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java [hunk 4]
```diff
@@ -31,11 +31,15 @@
...
-  private static final Pattern COVERED_LINES_PATTERN_1 = Pattern.compile(
-    ".*<script type=\"text/javascript\">\\s*+highlightRanges\\(\\[(.*?)\\]\\);\\s*+</script>.*",
+  private static final String TITLE_START = "<title>";
+  // the pattern for the information about a sequence point - (lineStart, columnStart, lineEnd, columnEnd, hits)
+  private static final Pattern SEQUENCE_POINT_PATTERN = Pattern.compile("\\[(\\d++),\\d++,(\\d++),\\d++,(\\d++)]");
+  private static final String SEQUENCE_POINTS_GROUP_NAME = "SequencePoints";
+  // the file coverage has a list of sequence points
+  // we use SEQUENCE_POINT_PATTERN below to avoid non-determinism in the regular expression, due to the `[` and `]` characters appearing multiple times
+  private static final Pattern FILE_COVERAGE_PATTERN = Pattern.compile(
+    ".*<script type=\"text/javascript\">\\s*+highlightRanges\\(\\[(?<" + SEQUENCE_POINTS_GROUP_NAME + ">" + SEQUENCE_POINT_PATTERN + "(," + SEQUENCE_POINT_PATTERN + ")*)]\\);\\s*+</script>.*",
```
Comment (pavel-mikula-sonarsource) [inline sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java:41]: I think the trailing `]` should be escaped
```suggestion
    ".*<script type=\"text/javascript\">\\s*+highlightRanges\\(\\[(?<" + SEQUENCE_POINTS_GROUP_NAME + ">" + SEQUENCE_POINT_PATTERN + "(," + SEQUENCE_POINT_PATTERN + ")*)\\]\\);\\s*+</script>.*",
```

**Review by pavel-mikula-sonarsource — CHANGES_REQUESTED** [review]
Regex nitpick and small improvement suggestion

File: sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (pavel-mikula-sonarsource) [reply sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java]: The new version and naming is awesome! It's pretty clear now and it actually all fits together now.

File: sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java (hunk 4 above)
Comment (andrei-epure-sonarsource) [reply sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java:41]: I fixed a code smell by not escaping it. and the unit tests pass.

could you help with a test case to cover adding it back?

File: sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/DotCoverReportParserTest.java [hunk 5]
```diff
@@ -55,17 +53,56 @@ public void prepare() {
 
   @Test
   public void no_title() {
-    thrown.expect(IllegalArgumentException.class);
-    thrown.expectMessage("The report contents does not match the following regular expression: .*?<title>(.*?)</title>.*");
-    new DotCoverReportParser(alwaysTrue).accept(new File("src/test/resources/dotcover/no_title.html"), mock(Coverage.class));
+    DotCoverReportParser parser = new DotCoverReportParser(alwaysTrue);
```
Comment (pavel-mikula-sonarsource) [inline sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/DotCoverReportParserTest.java:56]: Codesmell: SL complains about merging these 3 tests to a single, parametrized one.

File: sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java (hunk 4 above)
Comment (pavel-mikula-sonarsource) [reply sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java]: Hmm, it shouldn't be there indeed. I've learned something new 🙂

File: sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java (hunk 3 above)
Comment (pavel-mikula-sonarsource) [reply sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java]: I meant it like this to respect previous comment about `getIndexOf`.
```
    private int getIndexOf(String fileContent, String tag, int startIndex) {
      int index = fileContent.indexOf(tag, startIndex);
      if (index == -1) {
        throw new IllegalArgumentException(String.format("The report does not contain a '%s' tag.", tag));
      }
      return index;
    }
```
and usage like
```
      int indexOfTitleStart = getIndexOf(contents, TITLE_START);
      int indexOfTitleEnd = getIndexOf(contents, "</title>", indexOfTitleStart);
      String lowerCaseAbsolutePath = fileContent.substring(indexOfTitleStart + TITLE_START.length(), indexOfTitleEnd);

```
We won't need so many constants as well, as stuff would not be repeated.

Comment (pavel-mikula-sonarsource) [reply sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java]: The </title><title> is such a corner case, that we can live with current error message. We could also update it to something like hardcoded `..not contain valid <title> tag..`

File: sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/DotCoverReportParserTest.java (hunk 5 above)
Comment (andrei-epure-sonarsource) [reply sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/DotCoverReportParserTest.java:56]: I know, but I'd have to update to JUnit5 for this and I don't want to do it in this PR.

The JUnit4 way of dealing with parameterized tests is depressing. I opened #4223 for updating to JUnit5.

Comment (andrei-epure-sonarsource) [reply sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/DotCoverReportParserTest.java:56]: (tried in some PR before to update the JUnit version, either for UTs or ITs, and there was a problem at that point - maybe a small one... so it's better to have a separate ticket)

**Review by pavel-mikula-sonarsource — CHANGES_REQUESTED** [review]
I've meanwhile added a comment to the `indexOf` thread above

File: sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java (hunk 3 above)
Comment (andrei-epure-sonarsource) [reply sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java]: (sorry, I misread your comment initially, makes sense)

File: sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java [hunk 6]
```diff
@@ -93,27 +95,31 @@ private String extractFileCanonicalPath(String contents) {
...
       }
     }
 
-    private void checkMatches(Matcher matcher) {
-      if (!matcher.matches()) {
-        throw new IllegalArgumentException("The report contents does not match the following regular expression: " + matcher.pattern().pattern());
+    private int getIndexOf(String fileContent, String tag, int startIndex) {
+      int index = fileContent.indexOf(tag, startIndex);
+      if (index == -1) {
+        throw new IllegalArgumentException("The report does not contain a vald '<title>...</title>' tag.");
```
Comment (pavel-mikula-sonarsource) [inline sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/DotCoverReportParser.java:120]: Typo
```suggestion
        throw new IllegalArgumentException("The report does not contain a valid '<title>...</title>' tag.");
```

**Review by pavel-mikula-sonarsource — APPROVED** [review]
LGTM, please fix the last typo before merging
