### PR TITLE
Fix coverage aggregation from multiple reports

### LINKED ISSUE #8696: Fix coverage aggregation from multiple reports
### Description

On sonar-dotnet build itself, we produce several coverage reports at the moment, each from a dedicated test project (here are the relevant fragments):
* [coverage.DotNetCoverageNet7.net7.0-windows.xml.txt](https://github.com/SonarSource/sonar-dotnet/files/14179714/coverage.DotNetCoverageNet7.net7.0-windows.xml.txt)
* [coverage.DotNetCoverageNet8.xml.txt](https://github.com/SonarSource/sonar-dotnet/files/14179715/coverage.DotNetCoverageNet8.xml.txt)
* [coverage.DotNetCoverageTestFramework.xml.txt](https://github.com/SonarSource/sonar-dotnet/files/14179716/coverage.DotNetCoverageTestFramework.xml.txt)
* [coverage.DotNetCoverageNet48.net48.xml.txt](https://github.com/SonarSource/sonar-dotnet/files/14179713/coverage.DotNetCoverageNet48.net48.xml.txt)

These gets all imported into coverage sensor and processed via our aggregation logic. For the production code in `SonarAnalyzer.TestFrameworkVerificationIssueValidationIssueLocationPair.cs` and [line 68](https://github.com/SonarSource/sonar-dotnet/blob/9.23.1.88495/analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/IssueLocationPair.cs#L68)
```
 else if (Expected is null)
```

this produces 2 out of 3 covered conditions that don't make sense.
image

We need to fix the aggregation.

### Situation

The affected production code is part of our test framework. It is tested:
* Directly on all paths via `coverage.DotNetCoverageTestFramework.xml.txt`
* Indirectly, mostly only on happy paths via `coverage.DotNetCoverageNet7.net7.0-windows.xml.txt` and `coverage.DotNetCoverageNet48.net48.xml.txt`
* Not at all via `coverage.DotNetCoverageNet8.xml.txt`, because it doesn't reach this error state in the current set of tests

### Coverage data

Coverage data contains expected values like this:

#### coverage.DotNetCoverageTestFramework.xml.txt
Indicates that there are 2 branches and both are visited
```
                <SequencePoint vc="70" uspid="198" ordinal="2" offset="54" sl="68" sc="14" el="68" ec="35" bec="2" bev="2" fileid="940" />
...
                <BranchPoint vc="52" uspid="204" ordinal="4" offset="60" sl="68" path="0" offsetend="65" fileid="940" />
                <BranchPoint vc="18" uspid="205" ordinal="5" offset="60" sl="68" path="1" offsetend="236" fileid="940" />
```

#### coverage.DotNetCoverageNet7.net7.0-windows.xml.txt and it's net48 counterpart 
Indicates that there are 2 branches, and one of them is visited - this is expected.
```
                <SequencePoint vc="2" uspid="198" ordinal="2" offset="54" sl="68" sc="14" el="68" ec="35" bec="2" bev="1" fileid="940" />
...
                <BranchPoint vc="2" uspid="204" ordinal="4" offset="60" sl="68" path="0" offsetend="65" fileid="940" />
                <BranchPoint vc="0" uspid="205" ordinal="5" offset="60" sl="68" path="1" offsetend="236" fileid="940" />

```

#### coverage.DotNetCoverageNet8.xml.txt
Indicates that there are 2 branches and none of them is visited from this test run - this is also expected
```
                <SequencePoint vc="0" uspid="198" ordinal="2" offset="54" sl="68" sc="14" el="68" ec="35" bec="2" bev="0" fileid="940" />
...
                <BranchPoint vc="0" uspid="204" ordinal="4" offset="60" sl="68" path="0" offsetend="65" fileid="940" />
                <BranchPoint vc="0" uspid="205" ordinal="5" offset="60" sl="68" path="1" offsetend="236" fileid="940" />
```

### PR DESCRIPTION
**Pull request by Tim-Pohlmann**
This reverts commit #9018 and fixes the root cause.

Fixes #8696

### CODE REVIEW

File: sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/OpenCoverReportParser.java [hunk 1]
```diff
@@ -158,7 +158,7 @@ private void handleBranchPointTag(XmlParserHelper xmlParserHelper) {
         int visitCount = xmlParserHelper.getRequiredIntAttribute("vc");
 
         if (coveredFile.isIndexed()) {
-          coverage.add(new BranchPoint(coveredFile.indexedPath, line, offset, offsetEnd, path, visitCount));
+          coverage.add(new BranchPoint(coveredFile.indexedPath, line, offset, offsetEnd, path, visitCount, file.getPath()));
```
Comment (CristianAmbrosini) [inline sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/OpenCoverReportParser.java:161]: Educational: is OpenCover the only tool that is using BranchPoint and doing branch analysis?

**Review by CristianAmbrosini — COMMENTED** [review]
I'll leave this first round of comments for the UTs, I'll need more focus for the implementation. I'll tackle it tomorrow 👍

File: sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/OpenCoverReportParser.java (hunk 1 above)
Comment (Tim-Pohlmann) [reply sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/OpenCoverReportParser.java:161]: The other tools do not use BranchPoints. If I understood Costin correctly, they do branch coverage in a more limited fashion.

File: sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/Coverage.java [hunk 2]
```diff
@@ -86,33 +87,12 @@ Map<Integer, Integer> hits(String file) {
...
-        }
-
-        if(groupsByKey.size() > 1) {
-          result.add(new BranchCoverage(line, groupsByKey.size(), coveredBranchPoints));
-        }
-      }
-    }
-
-    return result;
+      .collect(Collectors.groupingBy(BranchPoint::getStartLine)).entrySet().stream()
```
Comment (CristianAmbrosini) [inline sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/Coverage.java:92]: Is startLine considered the line in the .cs file or IL?

File: sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/Coverage.java [hunk 3]
```diff
@@ -132,4 +112,21 @@ private void mergeLineHits(Coverage otherCoverage){
       }
     }
   }
+
+  private static BranchCoverage getBranchCoverage(int lineNumber, List<BranchPoint> branchPoints) {
+    // Mapping BranchPoints from different coverage reports is fragile due to potential differences in compilation.
+    // Therefore, we use a forgiving approach: First, count the number of BranchPoints per report and take the maximum. Then, map
+    // BranchPoints and count the ones that are covered. If the mapping did not go well, we might find too many covered BranchPoints.
+    // In this case, we cap the amount to the previously calculated maximum and assume all branches are covered.
+    int maxBranchPoints = branchPoints.stream()
```
Comment (CristianAmbrosini) [inline sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/Coverage.java:121]: Can we store the stream for reuse in both `maxBranchPoints` and `coveredBranchPoints`?

File: sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageTest.java [hunk 4]
```diff
@@ -202,16 +205,68 @@ public void givenMultipleBranchPointsPerLine_getBranchCoverage_returnsBranchCove
...
+    sut.add(new BranchPoint(secondPath, 1, 12, 14, 2, 0, coverageIdentifier));
 
-    assertThat(sut.getBranchCoverage(firstPath)).containsOnly(new BranchCoverage(1, 2, 2));
-    assertThat(sut.getBranchCoverage(secondPath)).containsOnly(new BranchCoverage(1, 3, 1));
+    assertThat(sut.getBranchCoverage(firstPath)).containsExactlyInAnyOrder(new BranchCoverage(1, 2, 2));
+    assertThat(sut.getBranchCoverage(secondPath)).containsExactlyInAnyOrder(new BranchCoverage(1, 3, 1));
+  }
+
+  @Test
+  public void givenBranchPointsFromFromDifferentReports_getBranchCoverage_returnsBranchCoverage(){
```
Comment (CristianAmbrosini) [inline sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/CoverageTest.java:223]: We don't have tests that cover real scenarios, just simulated ones. Are you confident enough that you'll manage to do a proper validation? You can try retrieving coverage data of some files/projects that might be affected and see how they are behaving with the new computation

**Review by CristianAmbrosini — CHANGES_REQUESTED** [review]
Left some suggestions

File: sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/Coverage.java (hunk 2 above)
Comment (Tim-Pohlmann) [reply sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/Coverage.java:92]: `.cs`

File: sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/Coverage.java (hunk 3 above)
Comment (Tim-Pohlmann) [reply sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/Coverage.java:121]: This is the beauty of Java streams! You cannot reuse them once they have been collected 😖

Comment (CristianAmbrosini) [reply sonar-dotnet-shared-library/src/main/java/org/sonar/plugins/dotnet/tests/Coverage.java:121]: I see, all good then!

File: its/projects/CoverageTest.MultipleFrameworks/TestProject/TestProject.csproj [hunk 5]
```diff
@@ -0,0 +1,21 @@
+﻿<Project Sdk="Microsoft.NET.Sdk">
+
+  <PropertyGroup>
+    <TargetFrameworks>net48;net7.0</TargetFrameworks>
+    <IsPackable>false</IsPackable>
+    <IsTestProject>true</IsTestProject>
+  </PropertyGroup>
+
+  <ItemGroup>
+    <PackageReference Include="altcover" Version="8.8.21" />
```
Comment (CristianAmbrosini) [inline its/projects/CoverageTest.MultipleFrameworks/TestProject/TestProject.csproj:10]: This is probably not useful since the .xml files are on disk.

File: its/src/test/java/com/sonar/it/csharp/CoverageTest.java [hunk 6]
```diff
@@ -89,6 +88,22 @@ void open_cover_on_MultipleProjects() throws Exception {
     assertCoverageMetrics("CoverageTest.MultipleProjects:SecondProject/FirstClass.cs", 11, 3, 10, 4);
   }
 
+  @Test
+  void open_cover_on_MultipleFrameworks() throws Exception {
+    BuildResult buildResult = analyzeMultipleFrameworksTestProject("sonar.cs.opencover.reportsPaths", "coverage.*.xml");
+    String s = buildResult.getLogs();
```
Comment (CristianAmbrosini) [inline its/src/test/java/com/sonar/it/csharp/CoverageTest.java:94]: I think this was a leftover from some debugging session, we should delete it

File: its/src/test/java/com/sonar/it/csharp/CoverageTest.java [hunk 7]
```diff
@@ -89,6 +88,22 @@ void open_cover_on_MultipleProjects() throws Exception {
...
+    assertThat(buildResult.getLogs()).contains(
+      "Sensor C# Tests Coverage Report Import",
+      "Coverage Report Statistics: 1 files, 1 main files, 1 main files with coverage, 0 test files, 0 project excluded files, 0 other language files.");
+    /*
+    MatchingBranchpoints_FullyCovered:        2/2
+    MatchingBranchpoints_PartiallyCovered:    1/2
+    NotMatchingBranchpoints_FullyCovered:     2/2
+    NotMatchingBranchpoints_PartiallyCovered: 2/2 This over-reporting is expected.
```
Comment (CristianAmbrosini) [inline its/src/test/java/com/sonar/it/csharp/CoverageTest.java:102]: Where are all the assertions for this?

File: its/src/test/java/com/sonar/it/csharp/CoverageTest.java [hunk 8]
```diff
@@ -202,6 +217,10 @@ private BuildResult analyzeMultipleProjectsTestProject(String coverageProperty,
     return Tests.analyzeProject(temp, "CoverageTest.MultipleProjects", "no_rule", coverageProperty, coverageFileName);
   }
 
+  private BuildResult analyzeMultipleFrameworksTestProject(String coverageProperty, String coverageFileNames) throws IOException {
+    return Tests.analyzeProject(temp, "CoverageTest.MultipleFrameworks", "no_rule", coverageProperty, coverageFileNames);
```
Comment (CristianAmbrosini) [inline its/src/test/java/com/sonar/it/csharp/CoverageTest.java:221]: Why is this a separate private method? It's called just once

**Review by CristianAmbrosini — CHANGES_REQUESTED** [review]
Left a few more comments. We can clarify them tomorrow. Additionally, I don't understand why the `its/projects/CoverageTest.MultipleFrameworks/coverage.net7.0.xml` file is >50'000 lines, while the net48 is just 444

File: its/src/test/java/com/sonar/it/csharp/CoverageTest.java (hunk 8 above)
Comment (Tim-Pohlmann) [reply its/src/test/java/com/sonar/it/csharp/CoverageTest.java:221]: For consistency with `analyzeCoverageTestProject` and `analyzeMultipleProjectsTestProject`.

**Review by CristianAmbrosini — APPROVED** [review]
LGTM!
