### PR TITLE
Fix S1075 FN: default parameters

### LINKED ISSUE #8129: Fix S1075 FN: default parameters
The rule does not take into account the primary constructor, lambda's and methods default parameters.
```cs
﻿class PrimaryConstructor(string ctorParam = "file://blah.txt") // FN
{
    void Method(string methodParam = "file://blah.txt") // FN
    {
        var lambda = (string lambdaParam = "file://blah.txt") => lambdaParam; // FN
    }
}
```

### PR DESCRIPTION
**Pull request by cristian-ambrosini-sonarsource**
Fixes #8129

### CODE REVIEW

File: analyzers/src/SonarAnalyzer.VisualBasic/Rules/UriShouldNotBeHardcoded.cs [hunk 1]
```diff
@@ -21,38 +21,29 @@
...
+        protected override SyntaxKind[] StringConcatenateExpressions => new[] { SyntaxKind.AddExpression, SyntaxKind.ConcatenateExpression };
+        protected override SyntaxKind[] InvocationOrObjectCreationKind => new[] { SyntaxKind.InvocationExpression, SyntaxKind.ObjectCreationExpression };
 
-        protected override string GetLiteralText(LiteralExpressionSyntax literalExpression) => literalExpression?.Token.ValueText;
-
-        protected override ExpressionSyntax GetLeftNode(BinaryExpressionSyntax binaryExpression) => binaryExpression.Left;
-
-        protected override ExpressionSyntax GetRightNode(BinaryExpressionSyntax binaryExpression) => binaryExpression.Right;
+        protected override string GetLiteralText(LiteralExpressionSyntax literalExpression) =>
+            literalExpression?.Token.ValueText;
```
Comment (antonioaversa) [inline analyzers/src/SonarAnalyzer.VisualBasic/Rules/UriShouldNotBeHardcoded.cs:32]: C# and VB.NET implementations are exactly the same, except for the namespace of `LiteralExpressionSyntax`. While the base class takes a `TLiteralExpressionSyntax`, I guess you 
can't define the implementation at base level, because the C# version and the VB.NET version of the class don't share a common ancestor having `Token` defined.
If that's the case, what about extending the language facade, and in particular the `SyntaxFacade`?
The method can give back a generic `SyntaxToken` or even just a string corresponding to `ValueText`. We already have a method doing that for an expression:
```cs
    public string GetName(SyntaxNode expression) =>
        expression.GetName();
```

File: analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxFacade.cs [hunk 2]
```diff
@@ -88,6 +88,9 @@ node switch
     public override IEnumerable<SyntaxNode> EnumMembers(SyntaxNode @enum) =>
         @enum == null ? Enumerable.Empty<SyntaxNode>() : Cast<EnumStatementSyntax>(@enum).Parent.ChildNodes().OfType<EnumMemberDeclarationSyntax>();
 
+    public override int? GetArgumentIndex(SyntaxNode node) =>
```
Comment (antonioaversa) [inline analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxFacade.cs:91]: Same as for C#: it would be better to rename `node` into `argument`.

File: analyzers/src/SonarAnalyzer.CSharp/Rules/UriShouldNotBeHardcoded.cs [hunk 3]
```diff
@@ -21,27 +21,29 @@
...
+        protected override SyntaxKind[] InvocationOrObjectCreationKind => new[] { SyntaxKind.InvocationExpression, SyntaxKind.ObjectCreationExpression };
 
-        protected override int? GetArgumentIndex(ArgumentSyntax argument) =>
-            (argument?.Parent as ArgumentListSyntax)?.Arguments.IndexOf(argument);
+        protected override string GetLiteralText(LiteralExpressionSyntax literalExpression) =>
+            literalExpression?.Token.ValueText;
 
-        protected override string GetDeclaratorIdentifierName(VariableDeclaratorSyntax declarator) =>
-            declarator?.Identifier.ValueText;
+        protected override SyntaxNode GetRelevantAncestor(SyntaxNode node)
```
Comment (antonioaversa) [inline analyzers/src/SonarAnalyzer.CSharp/Rules/UriShouldNotBeHardcoded.cs:34]: I have already mentioned a proposal to simplify the implementation of this method in the VB.NET implementation.
Looking now at the C# version of it, I am wondering whether it can be of general use, and if so, if it should abstracted away from here, and moved to the base class or to the relevant facade. 
Once simplified, however, I think it may not be needed/useful anymore, since the method would become a one-liner...
To be checked.

File: analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UriShouldNotBeHardcoded.CSharp12.cs [hunk 4]
```diff
@@ -1,7 +1,10 @@
...
+﻿class PrimaryConstructor(string ctorParamUri = "file://blah.txt", // Noncompliant
+                         string ctorParam = "file://blah.txt") // Compliant
 {
-    void Method(string methodParam = "file://blah.txt") // FN
+    void Method(string methodParamUri = "file://blah.txt", // Noncompliant
+                string methodParam = "file://blah.txt") // Compliant
     {
-        var lambda = (string lambdaParam = "file://blah.txt") => lambdaParam; // FN
+        var lambda = (string lambdaParamUri = "file://blah.txt") => lambdaParamUri; // Noncompliant
+        var lambda2 = (string lambdaParam = "file://blah.txt") => lambdaParam; // Compliant
```
Comment (antonioaversa) [inline analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UriShouldNotBeHardcoded.CSharp12.cs:8]: Can we add some tests:
- having multiple non-compliances (with location assertion)
- combining compliant and non-compliant cases
- using a different type than `string`, but still compatible with a string literal (e.g. `IComparable uri = "a string"`

I am also wondering how the rule behaves in presence of collections, and with collection expressions:
- `IList<string> uris1 = new[] { "C:/test.txt" };`
- `IList<string> uris2 = ["C:/test.txt"];`
- `string[][] urisMatrix1 = [["C:/test.txt"]];`
- `IDictionary<string, string> urisDict = new Dictionary<string, string> { ["a"] = "C:/test.txt" };`
- ...

**Review by antonioaversa — CHANGES_REQUESTED** [review]
A bit of refactoring and code factorization is required, as well as a few more test scenarios.

File: analyzers/src/SonarAnalyzer.CSharp/Extensions/ArgumentSyntaxExtensions.cs [hunk 5]
```diff
@@ -47,5 +47,8 @@ internal static class ArgumentSyntaxExtensions
                 && TupleExpressionSyntaxWrapper.IsInstance(outerTuple)
                     ? (TupleExpressionSyntaxWrapper)outerTuple
                     : null;
+
+        internal static int? GetArgumentIndex(this ArgumentSyntax argument) =>
+            (argument?.Parent as ArgumentListSyntax)?.Arguments.IndexOf(argument);
```
[the remark this answers is not in the document]
Comment (cristian-ambrosini-sonarsource) [reply analyzers/src/SonarAnalyzer.CSharp/Extensions/ArgumentSyntaxExtensions.cs:52]: Yep I kept it as is (which is wrong for the reasons you explained), I'll remove the null check on `argument`

**Comment by antonioaversa** [comment]
@cristian-ambrosini-sonarsource I have also noticed that the new extension is not fully covered: https://sonarcloud.io/component_measures?id=sonaranalyzer-dotnet&pullRequest=8146&metric=new_coverage&view=list
The other cases of non-covered code may go away with some of the refactoring/factorization suggested in the review above.

File: analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UriShouldNotBeHardcoded.vb [hunk 6]
```diff
@@ -35,7 +35,7 @@ Namespace Tests.Diagnostics
             File.OpenRead("/etc/foo.csv") ' FN
         End Sub
 
-        Private Sub ValidCases(s As String)
+        Private Sub ValidCases(s As String, ByVal Optional methodParam As String = "file://blah.txt")
```
[the remark this answers is not in the document]
Comment (cristian-ambrosini-sonarsource) [reply analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UriShouldNotBeHardcoded.vb:38]: The rule, specifically for assignment, performs a camelCase split of the identifier and checks for certain keywords to be present:
```
"FILE",
"PATH",
"URI",
"URL",
"URN",
"STREAM"
```
so basically:
```cs
var webUri3 = "ftp://www.mywebsite.com"; // Noncompliant
var parameter = "ftp://www.mywebsite.com"; // Compliant
```

File: analyzers/src/SonarAnalyzer.VisualBasic/Rules/UriShouldNotBeHardcoded.cs [hunk 7]
```diff
@@ -21,38 +21,29 @@
...
+            if (parameter != null)
+            {
+                return parameter;
+            }
+            var variableDeclarator = node.FirstAncestorOrSelf<VariableDeclaratorSyntax>();
+            if (variableDeclarator != null)
+            {
+                return variableDeclarator;
+            }
+            return null;
```
[the remark this answers is not in the document]
Comment (cristian-ambrosini-sonarsource) [reply analyzers/src/SonarAnalyzer.VisualBasic/Rules/UriShouldNotBeHardcoded.cs:46]: Yes, it's correct, I was not sure if there were other ancestors that we could fit into this logic, and then I kept it as is. I think I prefer the slimmer version you suggested. Eventually, it might get expanded in the future.

File: analyzers/src/SonarAnalyzer.VisualBasic/Extensions/SyntaxNodeExtensions.cs [hunk 8]
```diff
@@ -96,6 +96,7 @@ static bool TakesExpressionTree(SymbolInfo info)
                 SimpleNameSyntax x => x.Identifier,
                 StructureBlockSyntax x => x.StructureStatement.Identifier,
                 QualifiedNameSyntax x => x.Right.Identifier,
+                VariableDeclaratorSyntax x => x.Names.FirstOrDefault()?.Identifier,
```
[the remark this answers is not in the document]
Comment (cristian-ambrosini-sonarsource) [reply analyzers/src/SonarAnalyzer.VisualBasic/Extensions/SyntaxNodeExtensions.cs:99]: I had the same question, I don't know exactly why is that

File: analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UriShouldNotBeHardcoded.CSharp12.cs (hunk 4 above)
Comment (cristian-ambrosini-sonarsource) [reply analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UriShouldNotBeHardcoded.CSharp12.cs:8]: Good catch! I added an issue #8172 for the collections.

File: analyzers/src/SonarAnalyzer.VisualBasic/Rules/UriShouldNotBeHardcoded.cs (hunk 1 above)
Comment (cristian-ambrosini-sonarsource) [reply analyzers/src/SonarAnalyzer.VisualBasic/Rules/UriShouldNotBeHardcoded.cs:32]: As we talked about, this will be done in a subsequent PR.

File: analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UriShouldNotBeHardcoded.CSharp12.cs (hunk 4 above)
Comment (cristian-ambrosini-sonarsource) [reply analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UriShouldNotBeHardcoded.CSharp12.cs:8]: Regarding IComparable, it cannot be tested with default parameters as the default values of a reference type other than a string can only be initialized with null (therefore not raising the issue). But it's covered on `UriShouldNotBeHardcoreded_CSharp_General` 👍

**Review by antonioaversa — APPROVED** [review]
LGTM

**Comment by cristian-ambrosini-sonarsource** [comment]
Peach validation:
Lost: /
Added:
- `public NativeAotToolchainBuilder UseNuGet(string microsoftDotNetILCompilerVersion = "", string nuGetFeedUrl = "https://api.nuget.org/v3/index.json")` TP
- `public Program(string url = "http://localhost:8080", int? seed = null)` TP
- `public async Task<JObject> GetRemoteDashboardContent(string section, string baseUrl = "https://dashboard.umbraco.com/")` TP
- `public async Task<IActionResult> GetRemoteDashboardCss(string section, string baseUrl = "https://dashboard.umbraco.org/")` TP
- `public async Task<List<HelpPage>> GetContextHelpForPage(string section, string tree, string baseUrl = "https://our.umbraco.com")` TP
