### PR TITLE
Fix S4275 FP when method is used inside getter or setter

### LINKED ISSUE #2435: Fix S4275 FP when method is used inside getter or setter
### Description

When the field is returned or set using a method call, the rule raises an issue.

The problem is that we don't really support inter-procedural analysis, so this FP is non-trivial to fix.

### Repro steps

```
    public class CrossProcedural
    {
        private int myValue;
        public int MyValue
        {
            // below there are two False Positives
            get => this.GetMyValue(); // Noncompliant {{Refactor this getter so that it actually refers to the field 'myValue'.}}
            set => this.SetMyValue(value); // Noncompliant {{Refactor this setter so that it actually refers to the field 'myValue'.}}
        }

        private int GetMyValue() => this.myValue;
        private void SetMyValue(int value) => this.myValue = value;
    }
```

### Related information

* SonarC# Version 7.14

### PR DESCRIPTION
**Pull request by pavel-mikula-sonarsource**
Fixes #2435

### CODE REVIEW

File: sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/PropertiesAccessCorrectField.cs [hunk 1]
```diff
@@ -114,7 +139,28 @@ protected override bool ShouldIgnoreAccessor(IMethodSymbol accessorMethod)
...
             getter.Parent.DescendantNodes().Any());
 
-        private static FieldData? ExtractFieldFromRefArgument(ArgumentSyntax argument, Compilation compilation)
+        private ExpressionSyntax SingleReturn(StatementSyntax body)
+        {
+            var returns = body.Parent.DescendantNodes().OfType<ReturnStatementSyntax>().ToArray();
+            return returns.Length == 1 ? returns.Single().Expression : null;
+        }
+
+        private ExpressionSyntax SingleInvocation(StatementSyntax body)
```
Comment (costin-zaharia-sonarsource) [inline sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/PropertiesAccessCorrectField.cs]: can be static

File: sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/PropertiesAccessCorrectField.cs [hunk 2]
```diff
@@ -114,7 +139,28 @@ protected override bool ShouldIgnoreAccessor(IMethodSymbol accessorMethod)
             (property.GetMethod?.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax() is AccessorStatementSyntax getter &&
             getter.Parent.DescendantNodes().Any());
 
-        private static FieldData? ExtractFieldFromRefArgument(ArgumentSyntax argument, Compilation compilation)
+        private ExpressionSyntax SingleReturn(StatementSyntax body)
```
Comment (costin-zaharia-sonarsource) [inline sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/PropertiesAccessCorrectField.cs]: can be static

File: sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesAccessCorrectField.cs [hunk 3]
```diff
@@ -554,4 +540,116 @@ public double SomeMember
...
+            {
+                SetByBody(value);
+            }
+        }
+
+        public int BodyValue_ // With "this."
+        {
+            get
+            {
+                return this.GetByBody();
```
Comment (costin-zaharia-sonarsource) [inline sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesAccessCorrectField.cs]: I think we should add a test also with more than one instruction

File: sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/PropertiesAccessCorrectField.cs [hunk 4]
```diff
@@ -50,27 +50,39 @@ protected override IEnumerable<FieldData> FindFieldAssignments(IPropertySymbol p
 
             // we only keep information for the first location of the symbol
             var assignments = new Dictionary<IFieldSymbol, FieldData>();
+            FillAssignments(setter, true);
+            // If there're no candidate variables, we'll try to inspect one local method invocation with value as argument
+            if (assignments.Count == 0
+                && SingleInvocation(setter) is ExpressionSyntax expression
```
Comment (costin-zaharia-sonarsource) [inline sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/PropertiesAccessCorrectField.cs]: SingleInvocation always returns ExpressionSyntax. Can use `{ }` if you want to check for null and assign a name to the return value.

File: sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/PropertiesAccessCorrectFieldBase.cs [hunk 5]
```diff
@@ -112,7 +112,7 @@ protected void CheckExpectedFieldIsUsed(IMethodSymbol methodSymbol, IFieldSymbol
             {
                 Location location = null;
                 string accessorType = null;
-                if (fields.Count() == 1)
+                if (fields.Count(x => x.UseFieldLocation) == 1)
```
Comment (costin-zaharia-sonarsource) [inline sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/PropertiesAccessCorrectFieldBase.cs]: fields parameter is iterated here more than once. We should use a List instead of IEnumerable<>.

File: sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/PropertiesAccessCorrectFieldBase.cs [hunk 6]
```diff
@@ -145,6 +145,16 @@ protected IList<PropertyData> CollectPropertyData(IEnumerable<IPropertySymbol> p
             return allPropertyData;
         }
 
+        protected SyntaxNode FindInvokedMethod(Compilation compilation, INamedTypeSymbol containingType, SyntaxNode expression) =>
```
Comment (costin-zaharia-sonarsource) [inline sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/PropertiesAccessCorrectFieldBase.cs]: can be static

File: sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/PropertiesAccessCorrectFieldBase.cs [hunk 7]
```diff
@@ -145,6 +145,16 @@ protected IList<PropertyData> CollectPropertyData(IEnumerable<IPropertySymbol> p
...
+            compilation.GetSemanticModel(expression.SyntaxTree) is SemanticModel semanticModel
+            && semanticModel.GetSymbolInfo(expression).Symbol is ISymbol invocationSymbol
+            && invocationSymbol.ContainingType == containingType
+            && invocationSymbol.DeclaringSyntaxReferences.Length == 1
+            && invocationSymbol.DeclaringSyntaxReferences.Single().GetSyntax() is SyntaxNode invokedMethod
```
Comment (costin-zaharia-sonarsource) [inline sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/PropertiesAccessCorrectFieldBase.cs]: We can use object pattern `is { }` instead of `is SemanticModel`, `is ISymbol` and `is SyntaxNode`. Specifying the same type as the method return type is misleading.

File: sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PropertiesAccessCorrectField.cs [hunk 8]
```diff
@@ -49,27 +50,41 @@ protected override IEnumerable<FieldData> FindFieldAssignments(IPropertySymbol p
 
             // we only keep information for the first location of the symbol
             var assignments = new Dictionary<IFieldSymbol, FieldData>();
-            foreach (var node in setter.DescendantNodes())
+            FillAssignments(setter, true);
+
+            // If there're no candidate variables, we'll try to inspect one local method invocation with value as argument
+            if (assignments.Count == 0
+                && (setter.ExpressionBody()?.Expression ?? SingleInvocation(setter.Body)) is ExpressionSyntax expression
```
Comment (costin-zaharia-sonarsource) [inline sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PropertiesAccessCorrectField.cs]: Can use object pattern (`is { }`) instead of `is ExpressionSyntax `

File: sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PropertiesAccessCorrectField.cs [hunk 9]
```diff
@@ -49,27 +50,41 @@ protected override IEnumerable<FieldData> FindFieldAssignments(IPropertySymbol p
...
-                    assignments.Add(foundField.Value.Field, foundField.Value);
-                }
+                FillAssignments(invokedMethod, false);
             }
+
             return assignments.Values;
 
             bool IsRefOrOut(SyntaxToken node) => node.IsKind(SyntaxKind.RefKeyword) || node.IsKind(SyntaxKind.OutKeyword);
+
+            void FillAssignments(SyntaxNode root, bool useFieldLocation)
```
Comment (costin-zaharia-sonarsource) [inline sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PropertiesAccessCorrectField.cs]: I think it would be better to extract this outside of this method. The method is big enough already and like this it hides the dependencies (compilation, assignments, IsRefOrOut)

File: sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PropertiesAccessCorrectField.cs [hunk 10]
```diff
@@ -119,9 +147,28 @@ protected override bool ShouldIgnoreAccessor(IMethodSymbol accessorMethod)
             (property.GetMethod?.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax() is AccessorDeclarationSyntax getter &&
             getter.DescendantNodes().Any());
 
-        private static FieldData? ExtractFieldFromExpression(AccessorKind accessorKind,
-            ExpressionSyntax expression,
-            Compilation compilation)
+        private ExpressionSyntax SingleReturn(BlockSyntax body)
```
Comment (costin-zaharia-sonarsource) [inline sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PropertiesAccessCorrectField.cs]: can be static

File: sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PropertiesAccessCorrectField.cs [hunk 11]
```diff
@@ -119,9 +147,28 @@ protected override bool ShouldIgnoreAccessor(IMethodSymbol accessorMethod)
...
+        {
+            var returns = body.DescendantNodes().OfType<ReturnStatementSyntax>().ToArray();
+            return returns.Length == 1 ? returns.Single().Expression : null;
+        }
+
+        private ExpressionSyntax SingleInvocation(BlockSyntax body)
```
Comment (costin-zaharia-sonarsource) [inline sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PropertiesAccessCorrectField.cs]: can be static

File: sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PropertiesAccessCorrectField.cs [hunk 12]
```diff
@@ -135,14 +182,14 @@ protected override bool ShouldIgnoreAccessor(IMethodSymbol accessorMethod)
             if (strippedExpression is IdentifierNameSyntax &&
                 semanticModel.GetSymbolInfo(strippedExpression).Symbol is IFieldSymbol field)
             {
-                return new FieldData(accessorKind, field, strippedExpression);
+                return new FieldData(accessorKind, field, strippedExpression, useFieldLocation);
             }
             // Check for "this.foo"
             else if (strippedExpression is MemberAccessExpressionSyntax member &&
```
Comment (costin-zaharia-sonarsource) [inline sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PropertiesAccessCorrectField.cs]: The else is not really needed since the first if returns directly.

File: sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesAccessCorrectField.cs [hunk 13]
```diff
@@ -554,4 +540,116 @@ public double SomeMember
...
+        private int tooNested;
+        private int tooComplex;
+
+        public int ExpressionValue
+        {
+            get => GetByExpression();
+            set => SetByExpression(value);
+        }
+
+        public int ExpressionValue_ // With "this."
```
[the remark this answers is not in the document]
Comment (pavel-mikula-sonarsource) [reply sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/PropertiesAccessCorrectField.cs]: Yes, _ are ignored. See documentation of `PropertyToFieldMatcher` class in `PropertiesAccessCorrectFieldBase.cs`. I believe that test case `NonCompliant_UnderscoresInNamesAndCasing` on line 45 covers this.

Purpose of this _ here was to reduce scaffolding noise in order to test "this." usage (it requires different handling). I'll update the RSPEC.

File: sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PropertiesAccessCorrectField.cs (hunk 12 above)
Comment (pavel-mikula-sonarsource) [reply sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/PropertiesAccessCorrectField.cs]: I prefer to keep it for readability. It is else-if logic.

File: sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/PropertiesAccessCorrectField.cs [hunk 14]
```diff
@@ -124,15 +170,13 @@ protected override bool ShouldIgnoreAccessor(IMethodSymbol accessorMethod)
...
             }
             return null;
         }
 
-        private static FieldData? ExtractFieldFromExpression(AccessorKind accessorKind,
-            ExpressionSyntax expression,
-            Compilation compilation)
+        private static FieldData? ExtractFieldFromExpression(AccessorKind accessorKind, ExpressionSyntax expression, Compilation compilation, bool useFieldLocation)
         {
             var semanticModel = compilation.GetSemanticModel(expression.SyntaxTree);
```
[the remark this answers is not in the document]
Comment (pavel-mikula-sonarsource) [reply sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/PropertiesAccessCorrectField.cs]: It's also used by `IsFieldOrWithEvents` local function in the first if branch.

File: sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/PropertiesAccessCorrectField.cs [hunk 15]
```diff
@@ -145,16 +189,16 @@ protected override bool ShouldIgnoreAccessor(IMethodSymbol accessorMethod)
             // Check for direct field access: "Foo"
             if (strippedExpression is IdentifierNameSyntax && IsFieldOrWithEvents(out var directSymbol))
             {
-                return new FieldData(accessorKind, directSymbol, strippedExpression);
+                return new FieldData(accessorKind, directSymbol, strippedExpression, useFieldLocation);
             }
             else
             {
```
[the remark this answers is not in the document]
Comment (pavel-mikula-sonarsource) [reply sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/PropertiesAccessCorrectField.cs]: I prefer to keep it for readability. It is else-if logic.

File: sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/PropertiesAccessCorrectField.cs [hunk 16]
```diff
@@ -145,16 +189,16 @@ protected override bool ShouldIgnoreAccessor(IMethodSymbol accessorMethod)
...
                 // Check for "Me.Foo"
                 if (strippedExpression is MemberAccessExpressionSyntax member &&
-                    member.Expression is MeExpressionSyntax thisExpression &&
-                    IsFieldOrWithEvents(out var meSymbol))
+                    member.Expression is MeExpressionSyntax &&
+                    semanticModel.GetSymbolInfo(strippedExpression).Symbol is IFieldSymbol field2)
```
[the remark this answers is not in the document]
Comment (pavel-mikula-sonarsource) [reply sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/PropertiesAccessCorrectField.cs]: Probably refactoring artifact. Fixed.

File: sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/PropertiesAccessCorrectFieldBase.cs [hunk 17]
```diff
@@ -145,34 +171,23 @@ protected IList<PropertyData> CollectPropertyData(IEnumerable<IPropertySymbol> p
...
-         * - directly via an assignment
-         * - indirectly, when passed as 'out' or 'ref' parameter
-         */
-        protected abstract IEnumerable<FieldData> FindFieldAssignments(IPropertySymbol property, Compilation compilation);
-        protected abstract IEnumerable<FieldData> FindFieldReads(IPropertySymbol property, Compilation compilation);
-        protected abstract bool ImplementsExplicitGetterOrSetter(IPropertySymbol property);
-        protected abstract bool ShouldIgnoreAccessor(IMethodSymbol accessorMethod);
-
-
         protected struct PropertyData
```
Comment (costin-zaharia-sonarsource) [inline sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/PropertiesAccessCorrectFieldBase.cs]: not really related to this commit but I noticed that we could make this: "private readonly struct" and it would be nice.

File: sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/PropertiesAccessCorrectFieldBase.cs [hunk 18]
```diff
@@ -145,34 +171,23 @@ protected IList<PropertyData> CollectPropertyData(IEnumerable<IPropertySymbol> p
...
         {
             public PropertyData(IPropertySymbol propertySymbol, IEnumerable<FieldData> read, IEnumerable<FieldData> updated,
                 bool ignoreGetter, bool ignoreSetter)
             {
                 PropertySymbol = propertySymbol;
-                ReadFields = read;
-                UpdatedFields = updated;
+                ReadFields = read.ToImmutableArray();
```
Comment (costin-zaharia-sonarsource) [inline sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/PropertiesAccessCorrectFieldBase.cs]: This is nice but it would make sense in this case that both FindFieldAssignments and FindFieldReads to return ImmutableArray<T>. What do you think?

File: sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/PropertiesAccessCorrectField.cs (hunk 14 above)
[the remark this answers is not in the document]
Comment (costin-zaharia-sonarsource) [reply sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/PropertiesAccessCorrectField.cs]: true, that's one reason why I prefer to extract local functions when the methods get big; it make the code hard to read :)

[the remark this answers is not in the document]
Comment (pavel-mikula-sonarsource) [reply sonaranalyzer-dotnet/src/SonarAnalyzer.VisualBasic/Rules/PropertiesAccessCorrectField.cs]: It's not hard to read/understand. It's hard to review 😄

File: sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/PropertiesAccessCorrectFieldBase.cs (hunk 18 above)
Comment (pavel-mikula-sonarsource) [reply sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Rules/PropertiesAccessCorrectFieldBase.cs]: I considered that and decided to go with this version to remove unneeded duplication. It's PropertyData that really needs ImmutableArray, so it make sense to me that this is the single point responsible of doing so.

**Comment by chucklu** [comment]
@pavel-mikula-sonarsource  We are using Version 8.4.2 (build 36762) of sonarqube,  and the same problem still exists.

**Comment by pavel-mikula-sonarsource** [comment]
Hi @chucklu, can you please create a new issue with a reproducer and CSharp analyzer plugin version used? This is just a PR that was merged and closed.

There should be analyzer for C# 8.9 embedded in SQ 8.4.2.

**Comment by chucklu** [comment]
@pavel-mikula-sonarsource  Is it possible to reopen https://github.com/SonarSource/sonar-dotnet/issues/2435, since it's the same issue.

**Comment by pavel-mikula-sonarsource** [comment]
@chucklu We don't reopen issues released to milestones. Please create a new one, because your issue doesn't seem to be relevant to SonarC# Version 7.14 as reported with #2435
