### PR TITLE
Fail fast for SonarScanner for MSBuild <= 3.0

### LINKED ISSUE #3593: Fail fast for SonarScanner for MSBuild <= 3.0
Support for SonarScanner for MSBuild 3.0 was removed in previous release 8.12

We should fail fast the analysis in case that the `roslyn.reportFilePaths` property is missing for all projects (SQ modules).

We cannot fail fast when `analyzer.projectOutPaths` is missing because we intentionally don't generate the property for test projects. And solution containing only test projects would fail to analyze.

### PR DESCRIPTION
**Pull request by pavel-mikula-sonarsource**
Fixes #3593

### CODE REVIEW

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/DotNetSensor.java [hunk 1]
```diff
@@ -94,13 +94,14 @@ private void executeInternal(SensorContext context) {
...
 
     List<RoslynReport> roslynDirs = reportPathCollector.roslynDirs();
-    if (!roslynDirs.isEmpty()) {
-      Map<String, List<RuleKey>> activeRoslynRulesByPartialRepoKey = activeRoslynRulesByPartialRepoKey(pluginMetadata, context.activeRules()
-        .findAll()
-        .stream()
-        .map(ActiveRule::ruleKey)
-        .collect(toList()));
-      roslynDataImporter.importRoslynReports(roslynDirs, context, activeRoslynRulesByPartialRepoKey, toRealPath);
+    if (roslynDirs.isEmpty()) {
```
Comment (andrei-epure-sonarsource) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/DotNetSensor.java]: is it possible that a project without any issues won't end up with any roslynDirs? or are these created during the BEGIN step by the scanner?

Comment (andrei-epure-sonarsource) [reply sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/DotNetSensor.java]: in `org/sonarsource/dotnet/shared/plugins/AbstractModuleConfiguration.java` I see

```

  /**
   * Returns path of the directory containing all protobuf files, if:
   * - Property with it's location is defined
   * - The directory exists
   * - The directory contains at least one protobuf
   */
  public List<Path> protobufReportPaths() {
```

Comment (andrei-epure-sonarsource) [reply sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/DotNetSensor.java]: it can be easily tested with an IT that has no issues

**Review by andrei-epure-sonarsource — CHANGES_REQUESTED** [review]
would it be worth to add an IT with an "clean code project" with no issues?

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/DotNetSensor.java (hunk 1 above)
Comment (pavel-mikula-sonarsource) [reply sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/DotNetSensor.java]: Generation of the file is configured by `SonarQube.Integration.targets`. It's not configured when `SonarQubeExclude` is present. So in case all projects will have `SonarQubeExclude` we'll fail the analysis. But that kinda makes sense.

Project with no issues will still generate file with empty `results`, I've verified that: 
```
{
  "$schema": "http://json.schemastore.org/sarif-1.0.0",
  "version": "1.0.0",
  "runs": [
    {
      "tool": {
        "name": "Microsoft (R) Visual Basic Compiler",
        "version": "3.5.0.0",
        "fileVersion": "3.5.0-beta4-20153-05 (20b9af91)",
        "semanticVersion": "3.5.0",
        "language": "en-US"
      },
      "results": [
      ]
    }
  ]
}
```

Comment (pavel-mikula-sonarsource) [reply sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/DotNetSensor.java]: This PR is not related to `protobufReportPaths`, see issue description #3593

**Comment by pavel-mikula-sonarsource** [comment]
`NoSonarTest` seems that it doesn't contain any issues and would fail in that case.

**Comment by pavel-mikula-sonarsource** [comment]
Similar for `DoNotAnalyzeTestFilesTest`

**Review by andrei-epure-sonarsource — APPROVED** [review]
lgtm
