### PR TITLE
Ensure we don't fail when the issue message is missing

### LINKED ISSUE #5034: End step is failing if a rule raises an issue without a message
### Description

End step is failing if a rule raises an issue without a message

### Repro steps

Try to import a Sarif report with an issue without a message.

### Known workarounds

Please provide a description of any known workarounds.

### Related information

* C#/VB.NET Plugins version 8.30.0.37606

### PR DESCRIPTION
**Pull request by costin-zaharia-sonarsource**
- add a warning for this case

Fixes #5034

### CODE REVIEW

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/sarif/SarifParser10.java [hunk 1]
```diff
@@ -102,7 +105,10 @@ private void handleIssue(JsonObject resultObj, SarifParserCallback callback) {
     }
 
     String ruleId = resultObj.get("ruleId").getAsString();
-    String message = resultObj.get("message").getAsString();
+    String message = resultObj.has("message") ? resultObj.get("message").getAsString() : null;
+    if (message == null){
+      LOG.warn("Issue raise without a message for rule {}. Content: {}.", ruleId, resultObj.toString());
```
Comment (csaba-sagi-sonarsource) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/sarif/SarifParser10.java:110]:
```suggestion
      LOG.warn("Issue raised without a message for rule {}. Content: {}.", ruleId, resultObj.toString());
```

**Review by csaba-sagi-sonarsource — APPROVED** [review]
LGTM!
