### PR TITLE
TestFramework: Make failed assertions clickable

### LINKED ISSUE #8546: TestFramework: Make failed assertions clickable
Restore the ability to open any custom file and line from a failed test result window:
image

While the old implementation worked for a single stacktrace row, we need it to work for recapitulation of the whole failed UT.

### PR DESCRIPTION
**Pull request by pavel-mikula-sonarsource**
Fixes #8546 

The exact stack trace will change a bit to make it work in Rider too in #8725

### CODE REVIEW

File: analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifierException.cs [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+using SonarAnalyzer.TestFramework.Verification.IssueValidation;
+
+namespace SonarAnalyzer.Test.TestFramework;
+
+public sealed class DiagnosticVerifierException : AssertFailedException
+{
+    private readonly string stackTrace;
+
+    public override string StackTrace =>
+        stackTrace;
```
Comment (mary-georgiou-sonarsource) [inline analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifierException.cs:32]: it returns only a field so it can go in one line.
```suggestion
    public override string StackTrace => stackTrace;
```

File: analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifierException.cs [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+
+    internal DiagnosticVerifierException(List<VerificationMessage> messages) : base(messages.Select(x => x.FullDescription).JoinStr(Environment.NewLine))
+    {
+        if (messages.Count == 0)
+        {
+            throw new ArgumentException($"{nameof(messages)} cannot be empty", nameof(messages));
+        }
+        var builder = new StringBuilder();
+        foreach (var fileMessages in messages.Where(x => x.ShortDescription is not null && File.Exists(x.FullPath)).GroupBy(x => x.FullPath).OrderBy(x => x.Key))
```
Comment (mary-georgiou-sonarsource) [inline analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifierException.cs:41]:
```csharp
        messages.Where(x => x.ShortDescription is not null && File.Exists(x.FullPath)).GroupBy(x => x.FullPath).OrderBy(x => x.Key)
```

I find this a bit overloaded - I'd separate it maybe in its own variable or to not iterate twice in a local function.

**Review by mary-georgiou-sonarsource — APPROVED** [review]
LGTM
I left some suggestions and a coding style comment.

File: analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifierException.cs (hunk 2 above)
Comment (pavel-mikula-sonarsource) [reply analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifierException.cs:41]: What do you mean by "not iterate twice"?

I'll keep it, it's just below the edge to extract

Comment (mary-georgiou-sonarsource) [reply analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifierException.cs:40]: If you were to extract `var filtered =  messages.Where(x => x.ShortDescription is not null && File.Exists(x.FullPath)).GroupBy(x => x.FullPath).OrderBy(x => x.Key)` and then do `foreach (var message in filtered) ` you'd be iterating twice no?

Comment (pavel-mikula-sonarsource) [reply analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifierException.cs:40]: The `var filtered` doesn't evaluate the `messages` at all. It only creates a query for Where, GroupBy, OrderBy predicates.
Then, `foreach` will do first evaluation. There would need to be for example `.Count()` to iterate that twice.
