### PR TITLE
Fix S2368 FP/FN: Don't raise for extension methods and raise for constructors

### LINKED ISSUE #7329: Fix S2368 FP: Do not raise on extension methods when "this" is multidimensional array
### Description

More details can be found on [this community ticket](https://community.sonarsource.com/t/about-csharpsquid-s2368-and-extensions-methods/91769)

### Repro steps

```csharp
public static void MatrixForEach<T>(this T[,] dataMatrix, Action<T, int, int> action) // Do not raise here, this extension method is specifically made for multi-d matrices
{ 
  // code
}
```

### Expected behavior

Do not raise.

### Actual behavior

Raises.

### PR DESCRIPTION
**Pull request by sagi1623**
Fixes #7329
And handles ordinary constructor support from #8083

### CODE REVIEW

File: analyzers/src/SonarAnalyzer.VisualBasic/Rules/PublicMethodWithMultidimensionalArray.cs [hunk 1]
```diff
@@ -18,21 +18,21 @@
...
-        private static readonly ImmutableArray<SyntaxKind> kindsOfInterest = ImmutableArray.Create(SyntaxKind.SubStatement, SyntaxKind.FunctionStatement);
-        public override ImmutableArray<SyntaxKind> SyntaxKindsOfInterest => kindsOfInterest;
+[DiagnosticAnalyzer(LanguageNames.VisualBasic)]
+public sealed class PublicMethodWithMultidimensionalArray : PublicMethodWithMultidimensionalArrayBase<SyntaxKind>
+{
+    protected override ILanguageFacade<SyntaxKind> Language => VisualBasicFacade.Instance;
 
-        protected override SyntaxToken GetIdentifier(MethodStatementSyntax method) => method.Identifier;
+    protected override Location GetIssueLocation(SyntaxNode node) =>
+        node?.RemoveParentheses() switch
```
Comment (cristian-ambrosini-sonarsource) [inline analyzers/src/SonarAnalyzer.VisualBasic/Rules/PublicMethodWithMultidimensionalArray.cs:29]: Here you are passing `c.Node` to the method which should be not null by design, so `?` can be removed

Comment (cristian-ambrosini-sonarsource) [inline analyzers/src/SonarAnalyzer.VisualBasic/Rules/PublicMethodWithMultidimensionalArray.cs:29]: Same for `RemoveParentheses()`, we are passing a `MethodDeclaration` or a `ConstructorDeclaration` so most probably it's not needed and can be removed

**Review by cristian-ambrosini-sonarsource — CHANGES_REQUESTED** [review]
Let's try to bump a bit the coverage to reach >95%

**Review by cristian-ambrosini-sonarsource — APPROVED** [review]
LGTM
