### PR TITLE
Fix RegEx hotspots in DotCoverReportParser v2

### LINKED ISSUE #4194: Fix RegEx hotspots in DotCoverReportParser
Remove backtracking from Regex in `DotCoverReportParser`, as found on SonarCloud:
https://sonarcloud.io/project/security_hotspots?id=org.sonarsource.dotnet%3Asonar-dotnet&sinceLeakPeriod=true#

```
private static final Pattern TITLE_PATTERN = Pattern.compile(".*?<title>(.*?)</title>.*", Pattern.DOTALL);
private static final Pattern COVERED_LINES_PATTERN_1 = Pattern.compile(
    ".*<script type=\"text/javascript\">\\s*+highlightRanges\\(\\[(.*?)\\]\\);\\s*+</script>.*",
    Pattern.DOTALL);
```

### PR DESCRIPTION
**Pull request by pavel-mikula-sonarsource**
Fixes #4194

First commit is a cherry-pick from the original #4212 
Second commits fixes the SO issue by removing the regex.

### CODE REVIEW

File: sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/DotCoverReportParserTest.java [hunk 1]
```diff
@@ -101,6 +147,18 @@ public void valid() throws Exception {
...
 
+  @Test
+  public void valid_big() throws Exception {
+    Coverage coverage = new Coverage();
+    new DotCoverReportParser(alwaysTrue).accept(new File("src/test/resources/dotcover/valid_big.html"), coverage);
+
+    String filePath = new File("mylibrary\\calc.cs").getCanonicalPath();
+    assertThat(coverage.files()).containsOnly(filePath);
+    assertThat(coverage.hits(filePath)).hasSize(10000);
+    assertThat(logTester.logs(LoggerLevel.INFO).get(0)).startsWith("Parsing the dotCover report ");
```
Comment (andrei-epure-sonarsource) [inline sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/DotCoverReportParserTest.java:158]: could you check the number of `TRACE` statements? and also the number of `INFO` statements (to be clear if there's only one or more TRACE/INFO log lines)

File: sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/DotCoverReportParserTest.java [hunk 2]
```diff
@@ -101,6 +147,18 @@ public void valid() throws Exception {
       .startsWith("dotCover parser: found coverage for line '12', hits '0' when analyzing the path '");
   }
 
+  @Test
+  public void valid_big() throws Exception {
+    Coverage coverage = new Coverage();
+    new DotCoverReportParser(alwaysTrue).accept(new File("src/test/resources/dotcover/valid_big.html"), coverage);
```
Comment (andrei-epure-sonarsource) [inline sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/DotCoverReportParserTest.java:153]: do you think it's a good idea to, inside the `valid_big.html` file, replace the contents inside `Add10000()` with a placeholder, and generate the `value = value + 1;` statements here in the test? and create a temporary file from the template + code?

because having a 10K LOC file is difficult to handle: 
-  both to load (the IDE + plugins may be very slow), also github
- and to review historical diffs

**Review by andrei-epure-sonarsource — CHANGES_REQUESTED** [review]

File: sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/DotCoverReportParserTest.java (hunk 2 above)
Comment (pavel-mikula-sonarsource) [reply sonar-dotnet-shared-library/src/test/java/org/sonar/plugins/dotnet/tests/DotCoverReportParserTest.java:153]: The file review is one-off task. I don't expect any changes there in a future. So I don't think we need complicated scaffolding in this case. The plain file is simple and 100% sure to be big.

**Comment by pavel-mikula-sonarsource** [comment]
I tried to fix the code smell, but introducing parameterized tests goes into a Java dependency hell rabbit hole 🤯 So I'm not able to do it in reasonable time.

**Comment by andrei-epure-sonarsource** [comment]
RE: parameterized - JUnit4 parameterized tests are messy. If we are to invest time, we should upgrade to JUnit5 which makes it as easy as in .NET to write parameterized tests. We have an issue for it: https://github.com/SonarSource/sonar-dotnet/issues/4223

**Review by andrei-epure-sonarsource — APPROVED** [review]
LGTM
