### PR TITLE
Rule S2068: ensure the custom parameters are set

### LINKED ISSUE #2913: (Regression) Rule 2068: customized parameters not taken into account
On SonarQube 7.9
Test case: https://github.com/eric-therond-sonarsource/testcsharp/blob/master/Program.cs

With sonar-csharp-plugin-8.2.0.13504.jar:
1) A new default quality profile is setted with this parameterized rule:
sonarqube2
2) But the rule is not raised on lines 17 & 18:
sonarqube1

Expected behaviour like for sonar-csharp-plugin-7.15.0.8572.jar:
sonarqube3

### PR DESCRIPTION
**Pull request by costin-zaharia-sonarsource**
Fixes #2913

### CODE REVIEW

**Comment by andrei-epure-sonarsource** [comment]
@costin-zaharia-sonarsource could you also add a regression test for it, either in this PR (ideally) or in a separate one? see https://github.com/SonarSource/sonar-dotnet/blob/cc164f4b085cd025f6931157d99a8e0f8ed61562/its/src/test/java/com/sonar/it/csharp/AutoGeneratedTest.java#L84 as a model - although it's changing a project property rather than a rule parameter via the API - otherwise you could put a SonarLint.xml file and link it to the solution

You could also take a look at #2783 as it's in the same context

**Comment by costin-zaharia-sonarsource** [comment]
> https://github.com/SonarSource/sonar-dotnet/blob/cc164f4b085cd025f6931157d99a8e0f8ed61562/its/src/test/java/com/sonar/it/csharp/AutoGeneratedTest.java#L84
> 
> as a model - although it's changing a project property rather than a rule parameter via the API - otherwise you could put a SonarLint.xml file and link it to the solution

As far as I can tell the API does not support rule parameter customization. I will try the solution with linking the SonarLint.xml.

File: its/projects/DefaultRuleParametersCanBeCustomized/DefaultRuleParametersCanBeCustomized/DefaultRuleParametersCanBeCustomized.cs [hunk 1]
```diff
@@ -0,0 +1,13 @@
+﻿namespace Credentials
+{
+    public class Credentials
+    {
+        private const string Username = "admin";
+        private const string Password = "Password123";
+        private const string Usario = "admin";
```
Comment (andrei-epure-sonarsource) [inline its/projects/DefaultRuleParametersCanBeCustomized/DefaultRuleParametersCanBeCustomized/DefaultRuleParametersCanBeCustomized.cs]: the test is a bit misleading - I expect 'Usario' is 'username' and an issue is raised on it because 'usario' is in given as a name for credential, together with "password, pwd, senha" (senha=password in portuguese, apparently).

The problem is that an issue is raised on line 7 and not on line 5 and this leads to some cognitive overload when reading the test - why is the rule raising for portuguese username but not for english username?

So I would keep just 'senha' and keep the test easy to follow (avoid raising on 'username' and 'usario')
