### PR TITLE
Do not rethrow the exception in SarifParserCallbackImpl for invalid location for .razor/.cshtml files

### LINKED ISSUE #7878: Do not rethrow the exception in `SarifParserCallbackImpl` for invalid location for .razor/.cshtml files
Because of the following 3 roslyn/razor issues we might get an invalid mapped location so we need to be resilient.

- https://github.com/dotnet/razor/issues/9050
- https://github.com/dotnet/razor/issues/9051
- https://github.com/dotnet/roslyn/issues/69248

### PR DESCRIPTION
**Pull request by csaba-sagi-sonarsource**
Fixes #7878

### CODE REVIEW

File: sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/sarif/SarifParserCallbackImplTest.java [hunk 1]
```diff
@@ -407,6 +418,38 @@ public void should_map_rule_type() {
...
+  @Test
+  public void issue_with_invalid_precise_location_forCshtml_reports_on_line() {
+    assertIssueReportedOnLine("Dummy.cshtml");
+  }
+
+  private void assertIssueReportedOnLine(String fileName) {
+    callback = new SarifParserCallbackImpl(ctx, repositoryKeyByRoslynRuleKey, false, emptySet(), emptySet(), emptySet());
+
+    // We try to report an issue that contains an invalid startColumn (bigger than the line length) but with a valid start line
+    // So we expect the issue to be reported on the start line.
```
Comment (sebastien-marichal) [inline sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/sarif/SarifParserCallbackImplTest.java:435]: What about invalid {start|end} line?

I guess this is already handled

**Review by sebastien-marichal — APPROVED** [review]
LGTM!
Left a small question for my understanding.
