### PR TITLE
Fix FN S2857: Raise issues when in file scoped namespace - Support for File scoped namespace declaration

### LINKED ISSUE #5981: FN S2857: No issue is raised when in file scoped namespace
### Description

When the strings to be checked are in a file scoped namespace, no issues are raised.

### Repro steps

```csharp
using System;
using System.Data.SqlClient;
using Linq = System.Linq;

namespace Tests.Diagnostics;

record Record
{
    public void VariousSqlKeywords()
    {
        var select = "SELECT e.*, f" +
            "FROM DimEmployee AS e" + // FN
            "ORDER BY LastName;"; // FN
    }
}
```

### Related information

* C#/VB.NET Plugins version: 8.43.0.51858

### PR DESCRIPTION
**Pull request by mary-georgiou-sonarsource**
Fixes #5981 

In this PR:
- Filescope namespace support was added to the shimlayer
- Fixed the FN (no issues were raised when in filescoper namespace)
- Fixed UT where class was not in namespace and the rules was not triggered at all.

### CODE REVIEW

File: analyzers/src/SonarAnalyzer.ShimLayer.CodeGeneration/SyntaxLightupGenerator.cs [hunk 1]
```diff
@@ -982,6 +982,65 @@ private void GenerateSyntaxWrapperHelper(in GeneratorExecutionContext context, I
                     continue;
                 }
 
+                if (node.Name == "BaseNamespaceDeclarationSyntax")
```
Comment (csaba-sagi-sonarsource) [inline analyzers/src/SonarAnalyzer.ShimLayer.CodeGeneration/SyntaxLightupGenerator.cs:985]: If I am not mistaken `SonarAnalyzer.ShimLayer.CodeGeneration` is only used to generate the wrappers so we should be fine with updating the roslyn version to be able to use the `BaseNamespaceDeclarationSyntax`. 
@costin-zaharia-sonarsource as you have more knowledge in this area, could you please confirm this?
```suggestion
                if (node.Name == nameof(BaseNamespaceDeclarationSyntax))
```

**Review by csaba-sagi-sonarsource — APPROVED** [review]
Looks good, lets merge it as is, so the other tickets from the sprint are not blocked. Once Costin comes back with an answer, if upgrading the roslyn version is an option it can be done in a separate PR.
